Cassandra 4.0
mulesoft/docs-connectors pull request #1078
Opened 2020-10-06 16:02 UTC by dhirsch1

2020-10-30 14:48 UTC, valean27 commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-studio.adoc
> +. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
Can you please add here a description of the security tab as well?  I think I've put it only on design center doc. Thanks

2020-10-30 14:50 UTC, valean27 submitted a review, later dismissed

2020-11-03 16:49 UTC, valean27 approved these changes

2020-11-03 17:03 UTC, valean27 commented on salesforce/10.5/modules/ROOT/pages/index.adoc
> +<<<<<<< HEAD
>>>> These are some merging conflicts, please remove the wrong ones.

2020-11-03 17:03 UTC, valean27 approved these changes, later dismissed

2020-11-04 14:12 UTC, valean27 commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +Add a *Parse Template* component to create a template for an HTML form. The example uses this form to convey information for creating the table. (*Reviewers, is this text correct?*):
yes

2020-11-04 14:12 UTC, valean27 commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +*Reviewers, where is the information for this template? I assume it is in form.html, but where is the form put?*
form.html is located in main/resources of the demo

2020-11-04 14:13 UTC, valean27 commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +Add a *Transform Message* component to set Java variables based on the payload received from *HTTP Listener*: *Reviewers, is this description correct*?
yes

2020-11-04 14:13 UTC, valean27 commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +Add the *Create keyspace* operation to create the new keyspace for the new table: (*Reviewers: please correct and make this text better*)
Create a keyspace for the new table to exist in. The tables are created in a keyspace, so you need to create a keyspace first.

2020-11-04 14:14 UTC, valean27 commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +Add a *Transform Component* to set Java variables based on the payload received from *HTTP Listener*: ()*Reviewers, is this description correct*)?
yes

2020-11-04 14:16 UTC, valean27 commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +Add a *Create Table* operation to create a new table based on a POST request that uses the template created in the first flow: (*Reviewers, please make this text more accurate. I am guessing here.*)
Not sure what that description is but, we need to add a create table operation in ordeer to create that table on the keyspace that was created before, create table operations takes as parameters a keyspace name, a table name, and a list columns that have a name, a type and a flag if they are primary key or not.  I hope I gave you enough info.

2020-11-04 17:36 UTC, valean27 approved these changes, later dismissed

2020-11-04 19:12 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-config-topics.adoc
> +. In a separate terminal tab, verify that Cassandra is running:
```suggestion
. Restart Apache Cassandra.
. In a separate terminal tab, verify that Apache Cassandra is running:
```

2020-11-04 19:12 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-config-topics.adoc
> +. In a separate terminal tab, verify that Cassandra is running:
Just to make it consistent every time you call Cassandra.

2020-11-04 19:13 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-config-topics.adoc
> +The below operations accept some POJOs as input parameters, which are needed for the DataSense functionality:
```suggestion
The following operations accept some POJOs as input parameters, which are needed for the DataSense functionality:
```

2020-11-04 19:16 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-config-topics.adoc
> +`addNewColumn`, `changeColumnType`, `createKeyspace`, `createTable`, `deleteColumnsValue`, `deleteRows`, `dropColumn`, `dropKeyspace`, `dropTable`, `executeCQLQuery`, `getTableNamesFromKeyspace`, `re
```suggestion
* `addNewColumn` +
* `changeColumnType` +
* `createKeyspace` +
*`createTable` +
* `deleteColumnsValue` +
* `deleteRows` +
* `dropColumn` +
* `dropKeyspace` +
*  `dropTable` +
* `executeCQLQuery` +
* `getTableNamesFromKeyspace` +
* `renameColumn` +
* `select` +
* `update`
```

2020-11-04 19:17 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-config-topics.adoc
> +`addNewColumn`, `changeColumnType`, `createKeyspace`, `createTable`, `deleteColumnsValue`, `deleteRows`, `dropColumn`, `dropKeyspace`, `dropTable`, `executeCQLQuery`, `getTableNamesFromKeyspace`, `re
I think it's easier to scan, but feel free to update it or not.

2020-11-04 19:21 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-design-center.adoc
> +. Click the Cassandra connector to configure the host, port, keyspace, and authentication:
```suggestion
. Click Cassandra Connector to configure the host, port, keyspace, and authentication:
```

2020-11-04 19:27 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +* <<manipulate-data,Manipulate Data in an Apache Cassandra Database>>
```suggestion
* <<create-table,Create a New Apache Cassandra Table>> +
Creates a template for an HTML form to use to enter data for the new table, creates a keyspace for the new table, and then creates the table
* <<manipulate-data,Manipulate Data in an Apache Cassandra Database>>
Manipulate data in an Apache Casandra database by getting table names from a keyspace, performing CRUD operations, executing CQL queries and so on.
```

2020-11-04 19:28 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +* <<manipulate-data,Manipulate Data in an Apache Cassandra Database>>
Add an explanation sentence for the second example? Something like the above...

2020-11-04 19:30 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +This example variables for some field values. You can either:
```suggestion
This example uses variables for some field values. You can either:
```

2020-11-04 19:37 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +. On the Listener properties window, click the plus sign (*+*) next to the *Connector configuration* field to add a global element.
```suggestion
. On the *Listener* properties window, click the plus sign (*+*) next to the *Connector configuration* field to add a global element.
```

2020-11-04 19:39 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +. Select global element that you configured for the *Create keyspace* operation.
```suggestion
. Select the global element that you configured for the *Create keyspace* operation.
```

2020-11-04 19:40 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +. Run the Mule app.
```suggestion
. Save and run the Mule app.
```

2020-11-04 19:46 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-examples.adoc
> +
Here jumps directly to the XML sample of the application with the operations. I would add an intro line of this XML

2020-11-04 19:47 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-reference.adoc
> +Release Notes: xref:release-notes::connector/cassandra-connector-release-notes-mule-4.adoc[Cassandra Connector Release Notes]
```suggestion

```

2020-11-04 19:47 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-reference.adoc
> +Release Notes: xref:release-notes::connector/cassandra-connector-release-notes-mule-4.adoc[Cassandra Connector Release Notes]
This is in the box of the Connectors Landing page.

2020-11-04 19:50 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-reference.adoc
> +| Column Name a| String |  The name of the column to removed |  #[payload] |
```suggestion
| Column Name a| String |  The name of the column to remove |  #[payload] |
```

2020-11-04 19:52 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-reference.adoc
> +| Table a| String |  The name of the table in which the entity is updated |  | x
```suggestion
| Table a| String |  The name of the table in which to update the entity |  | x
```

2020-11-04 19:56 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-studio.adoc
> +. Configure the other connector fields.
```suggestion
. <<create-mule-project,Create a Mule project>>.
. <<add-connector-to-project,Add the connector to your Mule project>>.
. <<configure-input-source,Configure a source for the connector's flow>>.
. <<add-connector-operation,Add a connector operation to the flow>>.
. <<configure-global-element,Configure a global element for the connector>>.
. <<configure-other-fields,Configure the other connector fields>>.

```

2020-11-04 19:57 UTC, kevintroller commented on cassandra/4.0/modules/ROOT/pages/cassandra-connector-studio.adoc
> +|Endpoint Identification Algorithm | The endpoint identification algorithm used by clients to validate server host name.The default value is an empty string, which means it is disabled. Clients, incl
```suggestion
|Endpoint Identification Algorithm | The endpoint identification algorithm used by clients to validate server host name. The default value is an empty string, which means it is disabled. Clients, including client connections created by the broker for inter-broker communication, verify that the broker host name matches the host name in the brokers certificate.
```

2020-11-04 22:10 UTC, valkyrie69 requested changes
Please reinstate the page aliases for the Mule 3.9 topics.

2020-11-04 22:10 UTC, valkyrie69 commented on cassandra/0.3.9/modules/ROOT/pages/cassandra-connector-conf-task.adoc
> -:page-aliases: 3.9@mule-runtime::cassandra-connector-conf-task.adoc
These page aliases are specific to  Mule 3.9 and need to stay (page aliases that are specific to a particular version like in this case should not be removed).

2020-11-04 22:10 UTC, valkyrie69 commented on cassandra/0.3.9/modules/ROOT/pages/cassandra-connector-create-keyspace-task.adoc
> -:page-aliases: 3.9@mule-runtime::cassandra-connector-create-keyspace-task.adoc
Don't delete

2020-11-04 22:10 UTC, valkyrie69 commented on cassandra/0.3.9/modules/ROOT/pages/cassandra-connector-create-table-task.adoc
> -:page-aliases: 3.9@mule-runtime::cassandra-connector-create-table-task.adoc
Don't delete

2020-11-04 22:10 UTC, valkyrie69 commented on cassandra/0.3.9/modules/ROOT/pages/cassandra-connector-datatypes.adoc
> -:page-aliases: 3.9@mule-runtime::cassandra-connector-datatypes.adoc
Don't delete

2020-11-04 22:10 UTC, valkyrie69 commented on cassandra/0.3.9/modules/ROOT/pages/cassandra-connector-install-conf-task.adoc
> -:page-aliases: 3.9@mule-runtime::cassandra-connector-install-conf-task.adoc
Don't delete

2020-11-04 22:10 UTC, valkyrie69 commented on cassandra/0.3.9/modules/ROOT/pages/cassandra-connector-ops-reference.adoc
> -:page-aliases: 3.9@mule-runtime::cassandra-connector-ops-reference.adoc
Don't delete

2020-11-05 16:14 UTC, valkyrie69 approved these changes

2020-11-05 16:46 UTC, merged