Apache Kaka Connector 4.4.0
mulesoft/docs-connectors pull request #1153
Opened 2020-11-18 18:25 UTC by dhirsch1

2020-11-23 17:13 UTC, Santaionut requested changes

2020-11-23 17:13 UTC, Santaionut commented on kafka/4.4/modules/ROOT/pages/kafka-connector-reference.adoc
> +| Partition a| Number |  The partition number that will have its offset modified. |  | x
after partition parameter please add offset parameter. 
| Offset a| Number |  +++The offset value to commit for the configured partition.+++ |  | x

2020-11-23 17:13 UTC, Santaionut commented on kafka/4.4/modules/ROOT/pages/kafka-connector-reference.adoc
> +* KAFKA:TIMEOUT
after KAFKA:TIMEOUT please add * KAFKA:INPUT_TOO_LARGE

2020-11-23 17:13 UTC, Santaionut commented on kafka/4.4/modules/ROOT/pages/kafka-connector-reference.adoc
> +* KAFKA:RETRY_EXHAUSTED
before KAFKA:RETRY_EXHAUSTED please add * KAFKA:ALREADY_COMMITED

2020-11-24 07:01 UTC, Santaionut approved these changes, later dismissed

2020-11-24 08:13 UTC, FilipBogdanSV submitted a review, later dismissed

2020-11-24 22:21 UTC, valkyrie69 commented on kafka/4.4/antora.yml
> +    page-exchange-asset-id: mule-kafka-connector
I don't know why this keeps happening, but the page runtime version (supported Mule version) keeps disappearing from the yaml files and needs to be put back. This line needs to go underneath line 13:
`page-runtime-version: 4.1.1`

2020-11-24 22:21 UTC, valkyrie69 commented on kafka/4.4/modules/ROOT/pages/index.adoc
> +For compatibility information see the xref:release-notes::connector/kafka-connector-release-notes-mule-4.adoc[Apache Kafka Connector Release Notes].
Not important, but we can remove the release notes xref and just keep the text.

2020-11-24 22:21 UTC, valkyrie69 commented on kafka/4.4/modules/ROOT/pages/index.adoc
> +== Prerequisites
The index isn't updated to match the most current template, but it's optional whether or not you want to tackle that now. It's not high priority.

2020-11-24 22:21 UTC, valkyrie69 commented on kafka/4.4/modules/ROOT/pages/kafka-connector-reference.adoc
> +Release Notes: xref:release-notes::connector/kafka-connector-release-notes-mule-4.adoc[Apache Kafka Connector]
We can remove the xref since release notes link is in the info box now.

2020-11-24 22:21 UTC, valkyrie69 commented on kafka/4.4/modules/ROOT/pages/kafka-connector-reference.adoc
> +| TLS Configuration a| <<Tls>> a|  Defines a configuration for TLS, which can be used from both the client and server sides to secure communication for the Mule app. When using the HTTPS protocol, th
This description for TLS Configuration is different from the others.

2020-11-24 22:21 UTC, valkyrie69 commented on kafka/4.4/modules/ROOT/pages/kafka-connector-reference.adoc
> +| TLS Configuration a| <<Tls>> | Defines a TLS configuration, which can be used from both the client and server sides to secure communication for the Mule app. When using the HTTPS protocol, the HTTP
Just verify we are using the correct description for this field in all occurrences.

2020-11-25 14:47 UTC, dhirsch1 commented on kafka/4.4/modules/ROOT/pages/kafka-connector-reference.adoc
> +| TLS Configuration a| <<Tls>> a|  Defines a configuration for TLS, which can be used from both the client and server sides to secure communication for the Mule app. When using the HTTPS protocol, th
Verified this and was told to leave it as is.

2020-11-25 16:46 UTC, Mulesoft-Mysti commented on kafka/4.4/modules/ROOT/pages/kafka-connector-upgrade-migrate.adoc
> +Upgrade Anypoint Connector for Apache Kafka (Apache Kafka Connector) to version 4.3.
I am confused: the title says 4.x but the intro sentence says 4.3.
Is it Kafka 4.3 or Mule 4.3?

2020-11-25 16:46 UTC, Mulesoft-Mysti commented on kafka/4.4/modules/ROOT/pages/kafka-connector-upgrade-migrate.adoc
> +Upgrade Anypoint Connector for Apache Kafka (Apache Kafka Connector) to version 4.3.
Oh, is it "upgrade Kafka 4.x (any *Kafka* version 4.whatever) to *Mule* 4.3?

2020-11-25 16:47 UTC, Mulesoft-Mysti submitted a review, later dismissed
One question on the upgrade topic. If you make changes, feel free to slack me directly for a re-approval.

2020-11-25 16:54 UTC, Mulesoft-Mysti approved these changes

2020-11-26 16:25 UTC, merged