Javadoc for Google Sheets
mulesoft/docs-connectors pull request #1243
Opened 2021-01-27 15:50 UTC by dhirsch1

2021-03-08 19:04 UTC, gastonortiz requested changes

2021-03-08 19:04 UTC, gastonortiz commented on google-sheets/1.0/modules/ROOT/pages/google-sheets-connector-reference.adoc
> +| Scopes a| String |  The OAuth scopes to request during the dance. If not provided, it defaults to those in the annotation. |  +https://www.googleapis.com/auth/spreadsheets.readonly+ +https://www.go
Default scopes are:
"https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/drive.metadata.readonly"

2021-03-08 19:08 UTC, gastonortiz commented on google-sheets/1.0/antora.yml
> +    page-runtime-version: 1.0.0-alpha-001
Version is 1.0.0

2021-03-08 19:38 UTC, gastonortiz submitted a review, later dismissed

2021-03-08 21:44 UTC, varunmaker submitted a review, later dismissed

2021-03-08 22:09 UTC, valkyrie69 commented on google-sheets/1.0/antora.yml
> +    page-component-desc: xxx
Needs a one line description. Like:
Synchronizes data and automates business processes between Google Sheets and third-party applications, either on-premises or in the cloud.

2021-03-08 22:09 UTC, valkyrie69 commented on google-sheets/1.0/antora.yml
> +    page-runtime-version: 1.0.0
The page-runtime-version is not the connector version. The Runtime version is supposed to be the Mule runtime version. Most likely 4.2.1, but you can confirm with dev.

2021-03-08 22:09 UTC, valkyrie69 commented on google-sheets/1.0/modules/ROOT/pages/google-sheets-connector-studio.adoc
> +You can reference a configuration file that contains ANT-style property placeholders (recommended), or you can enter your authorization credentials in the global configuration properties. For informa
Make sure you run the link checker the xref here is improperly formatted and will break the build. It should be: 
xref:connectors::introduction/...

2021-03-08 22:09 UTC, valkyrie69 commented on google-sheets/1.0/modules/ROOT/pages/google-sheets-connector-studio.adoc
> +// Add link to connector reference and specific connector intro topic
Add the link to the connector reference

2021-03-08 22:09 UTC, valkyrie69 commented on google-sheets/1.0/modules/ROOT/pages/google-sheets-connector-xml-maven.adoc
> +the xref:google/google-sheets-connector-examples.adoc[Examples].
This xref will break the build.

2021-03-08 23:50 UTC, mcherem submitted a review, later dismissed
One comment on the pom file

2021-03-08 23:50 UTC, mcherem commented on google-sheets/1.0/modules/ROOT/pages/google-sheets-connector-xml-maven.adoc
> +	http://www.mulesoft.org/schema/mule/workday
Should line 42 be workday or google sheets?

2021-03-09 00:21 UTC, mcherem approved these changes

2021-03-09 00:23 UTC, merged