[EDITS]Copy to edit
mulesoft/docs-connectors pull request #1244
Opened 2021-01-27 19:36 UTC by mcherem

[EDITS]Copy to edit.

2021-01-28 00:04 UTC, kbostrom approved these changes
first half of CE

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +
edit request

this content is very similar to the X12 docs you just edited for me. I have done my best to incorporate those edits into the EDIFACT docs. Type: CE, Scope: all except lines 25-29 in index.adoc, Due: two days from start is fine.

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +If your implementation conventions differ from the standard, you can create schemas to describe your messages. Standard versions of the schemas for all defined EDIFACT messages and supported versions
Should these sentences be reversed?

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +You can configure schema locations in the Anypoint Studio XML view.
Omit: it's in the task steps.
```suggestion
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +. In Anypoint Studio, switch to the XML view by clicking **Configuration XML**.
To avoid repeating "in Anypoint Studio":
```suggestion
. Switch to the XML view by clicking *Configuration XML*.
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +After you create a global element in Studio for your EDIFACT EDI, configure any schemas and operations.
To me, this just sounds better? Your choice:
```suggestion
After you create a global element for your EDIFACT EDI in Studio, configure any schemas and operations.
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|XML Value |Studio Option
Should these columns be reversed, given the intro. that puts Studio config. first and XML second (Line 28)?

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|schemas=list of values |List of schema paths the connector can use. These paths can be either a file system or `classpath`.
```suggestion
|schemas=list of values |List of schema paths the connector can use. Each path can be either a file system or `classpath`.
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|separatorUsage="USE_DEFAULTS" "USE_SPECIFIED_FOR_WRITES" "USE_SPECIFIED_FOR_ALL" |Use specified separator or release characters as defaults for messages.
parallelism among column texts:
```suggestion
|separatorUsage="USE_DEFAULTS" "USE_SPECIFIED_FOR_WRITES" "USE_SPECIFIED_FOR_ALL" |Specification to use either specified separator or release characters as defaults for messages.
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +== Self Identification Parameters
```suggestion
== Self-Identification Parameters
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +Use these parameters to identify your side of the trading partner relationship.
```suggestion
Use these parameters to identify your side of the trading partner relationship:
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|XML Value |Studio Option
If you switch these, do so GLOBALLY in this file.

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|interchangeIdQualifierSelf |Interchange Sender or receiver ID qualifier (UNB2.2/UNB3.2).
```suggestion
|interchangeIdQualifierSelf |Interchange Sender or Receiver ID qualifier (UNB2.2/UNB3.2).
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|enforceReadCharacters="true" |Enforce valid characters for a Read. Only applies when using syntax levels `UNOA` and `UNOB`.
```suggestion
|enforceReadCharacters="true" |Enforce valid characters for a Read operation. Only applies when using syntax levels `UNOA` and `UNOB`.
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|requireUniqueInterchanges="true" |Require unique Interchange Control References (such as UNB.5). The default behavior records the interchange numbers previously processed and rejects duplicate inter
```suggestion
|requireUniqueInterchanges="true" |Require unique interchange control references (such as UNB.5). The default behavior records the interchange numbers previously processed and rejects duplicate interchange numbers from the same partner. It is derived from the interchange Sender and Receiver identification. Setting to `false` enables received interchange processing to continue and relies on the application flow to track the numbers and manage them appropriately.
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|requireUniqueInterchanges="true" |Require unique Interchange Control References (such as UNB.5). The default behavior records the interchange numbers previously processed and rejects duplicate inter
Evaluate whether this item and the one that follows need to have so much information in their description (compared to the others). Perhaps these details are covered elsewhere?

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|requireUniqueMessages="false" |Enforce globally unique Message Reference Numbers (UNH.1) for received messages. By default, message reference numbers need to be unique only within a particular inter
```suggestion
|requireUniqueMessages="false" |Enforce globally unique message reference numbers (UNH.1) for received messages. By default, message reference numbers need to be unique only within a particular interchange. Setting to `true` requires message reference numbers to be unique across all interchanges received from the same partner and application. This is derived from the interchange sender and recipient identification.
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|lineEnding="NONE" "LF" "CRLF" "CR" |Line ending to add between segments. Improves the readability of the output message text by adding line endings between segments.
Repetitive; merge all into one sentence?

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|enforceWriteCharacters="true" |Enforce valid characters for write. This applies when using syntax levels `UNOA` and `UNOB`.
```suggestion
|enforceWriteCharacters="true" |Enforce valid characters for a Write operation. This applies when using syntax levels `UNOA` and `UNOB`.
```

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +|enforceWriteCharacters="true" |Enforce valid characters for write. This applies when using syntax levels `UNOA` and `UNOB`.
GLOBALLY lowercase message reference numbers and interchange control reference.

2021-01-28 00:04 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +* https://help.mulesoft.com[MuleSoft Help Center]
BREAK here

2021-01-28 18:34 UTC, kbostrom approved these changes, later dismissed
done with second part CE request

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/edifact-edi-connector-config-topics.adoc
> +* https://help.mulesoft.com[MuleSoft Help Center]
RESUME

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +The  xref:edifact-edi-versions.adoc[supported EDIFACT versions] are provided.
passive

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +The  xref:edifact-edi-versions.adoc[supported EDIFACT versions] are provided.
```suggestion
The xref:edifact-edi-versions.adoc[supported EDIFACT versions] are provided.
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +* Purchased a MuleSoft license for Anypoint B2B
```suggestion
* A MuleSoft license for Anypoint B2B
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +[NOTE]
I probably commented on this being a Note in the previous edit. It seems too important to be a Note at the end of the prereqs and I wonder if there is not a prereq category for its content: could it be incorporated into "you must have" as "Memory sufficient to meet the requirement for..."?

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +EDIFACT Connector supports files of up to 15 MB in size, and the memory requirement is approximately 40 to 1.
Implement previous edit wordings for this same text.
Also, beware extra spaces.

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +For example, a 1-MB file requires up to 40 MB of memory to process, so it's important to consider this memory requirement in conjunction with your Transactions Per Second (TPS)  needs for large X12 f
```suggestion
For example, a 1-MB file requires up to 40 MB of memory to process, so it's important to consider this memory requirement in conjunction with your Transactions Per Second (TPS) needs for large X12 files.
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +The EDIFACT EDI Connector uses a YAML format called EDI Schema Language (ESL) to represent EDI schemas. Basic ESLs define the structure of EDI messages in terms of
```suggestion
The EDIFACT EDI Connector uses a YAML format called EDI Schema Language (ESL) to represent EDI schemas. Basic ESLs define the structure of EDI messages in terms of:
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +* groups, segments, composites, and elements
Begin each with init. cap. Also:
```suggestion
* Structures, known as _messages_ in EDIFACT terminology

* Groups, segments, composites, and elements
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +You can customize the EDIFACT schema definitions to suit your data by defining an overlay schema. An overlay schema is a type of ESL that enables you to modify a base schema, such as an EDIFACT D.98B
```suggestion
You can customize the EDIFACT schema definitions to suit your data by defining an _overlay schema_. An overlay schema is a type of ESL that enables you to modify a base schema, such as an EDIFACT D.98B ORDERS schema, with your specific conventions. You don't need an overlay schema if you're using the structure defined by the standard, but most EDI exchanges modify the base definitions in an implementation convention.
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +You can customize the EDIFACT schema definitions to suit your data by defining an overlay schema. An overlay schema is a type of ESL that enables you to modify a base schema, such as an EDIFACT D.98B
Do we need to explain this further:
"but most EDI exchanges modify the base definitions in an implementation convention."

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +You can also define your own schemas from scratch, or copy and edit a base EDIFACT schema definition to suit your data as shown in the  xref:x12-edi-connector::x12-edi-schema-language-reference.adoc[
GLOBALLY rewrite to avoid idiomatic language such as "from scratch."

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +You can also define your own schemas from scratch, or copy and edit a base EDIFACT schema definition to suit your data as shown in the  xref:x12-edi-connector::x12-edi-schema-language-reference.adoc[
Remove extra space.

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +
How many types of schemas are there: overlay, basic, full? In addition to out-of-the-box and custom?
Be sure that each term is made distinct; omit one of any pair or group that is used synonymously.
GLOBAL in all writing.

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +Use this connector to read or write EDIFACT documents into (or from) the canonical EDI message structure. This structure is a hierarchy of Java Maps and Lists. You use either DataWeave or code to man
```suggestion
Use this connector to read or write EDIFACT documents to (or from) the canonical EDI message structure. This structure is a hierarchy of Java Map and List objects. You use either DataWeave or code to manipulate them. Each transaction has its own structure, as defined in the schemas.
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +The message contains the following keys, some of which apply to either the Read operation or Write operation, as indicated:
```suggestion
The message contains the following keys, some of which apply to either the Read operation or the Write operation, as indicated:
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +The message contains the following keys, some of which apply to either the Read operation or Write operation, as indicated:
See above, and in the following table Description column, consistently capitalize Read operation and Write operation.

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +data element separator, component element separator, repetition separator, segment terminator, release character.
```suggestion
|Delimiters |An optional set of delimiters used in the message. If used in a read operation, the delimiters are based on the most recent interchange processed by a read operation. If used for a write operation, the delimiters override the values in the module configuration. The characters in the string of delimiters are interpreted based on their position in string, in the following order: data element separator, component element separator, repetition separator, segment terminator, and release character.
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +|Interchange |A map of UNB interchange header segment values. For a read message, the map is the actual data from the enclosing interchange. It is a single map linked from all messages in the interch
Replace value(s) with the most likely of value or values; never use this (s) structure.

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +|MessageHeader |Map of UNH message header segment values. This provides the actual header data for a Read operation, and enables you to provide overrides for for Write operation configuration setting
```suggestion
|MessageHeader |Map of UNH message header segment values. This provides the actual header data for a Read operation, and enables you to provide overrides for Write operation configuration settings.
```

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +Generated CONTRL functional acknowledgment messages differ from Received messages in their handling of interchange information:
GLOBALLY standardize between Received messages and received messages.

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +|Interchange |For functional acknowledgments generated by Receive processing, this map is a copy of the data for the containing interchange with Sender and Receiver identification components (UNB2.1/
unclear reference: "When writing a message, these values are used...." What is writing the message?

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +|Interchange |For functional acknowledgments generated by Receive processing, this map is a copy of the data for the containing interchange with Sender and Receiver identification components (UNB2.1/
Fragment:
For example, gathering messages with the same interchange values into a single interchange, regardless of whether the actual maps are the same.

2021-01-28 18:34 UTC, kbostrom commented on edifact-edi/2.2/modules/ROOT/edits/index.adoc
> +|Interchange |For functional acknowledgments generated by Receive processing, this map is a copy of the data for the containing interchange with Sender and Receiver identification components (UNB2.1/
ditto re. value or values rather than value(s); GLOBAL

2021-02-01 21:15 UTC, dhirsch1 requested changes

2021-02-01 21:15 UTC, dhirsch1 commented on edifact-edi/2.2/modules/ROOT/pages/index.adoc
> +|Delimiters |An optional set of delimiters used in the message. If used in a Read operation, the delimiters are based on the most recent interchange processed by a Read operation. If used for a write
Should "write operation" be "Write operation" for consistency with "Read operation"?

2021-02-01 21:28 UTC, dhirsch1 approved these changes

2021-02-01 22:03 UTC, merged