versioning
mulesoft/docs-connectors pull request #1378
Opened 2021-03-26 20:36 UTC by sathya0

2021-03-30 13:42 UTC, laszloczol approved these changes, later dismissed

2021-03-31 17:42 UTC, dhirsch1 commented on trello/1.2/antora.yml
> +    page-runtime-version: 4.2.2
In the index topic, it says the runtime version is 4.3.5.

2021-03-31 17:42 UTC, dhirsch1 commented on trello/1.2/modules/ROOT/pages/index.adoc
> +* Anypoint Studio version 7.3.5 or later
See my comment in the antora.yml file.

2021-03-31 17:47 UTC, dhirsch1 requested changes
Caught one thing wrong that was most likely there before this version

2021-03-31 17:56 UTC, dhirsch1 approved these changes

2021-03-31 18:00 UTC, merged