Add note for a known issue on stored procedure operation
mulesoft/docs-connectors pull request #14
Opened 2018-10-08 19:31 UTC by Bardammu

2018-10-08 19:42 UTC, ndinu requested changes

2018-10-08 19:42 UTC, ndinu commented on modules/ROOT/pages/db/db-connector-sp.adoc
> +For version lower or equals to 1.4.0 make sure that there is no whitespaces between the name of the stored procedure and the first parentheses.
For versions 1.4.0 or older make sure ...

2018-10-08 20:00 UTC, ndinu approved these changes

2018-10-09 14:23 UTC, dukesphere approved these changes

2018-10-09 14:23 UTC, merged