DOCS-10770-X12-2.6-ESB
mulesoft/docs-connectors pull request #1442
Opened 2021-04-30 14:09 UTC by emileeburkeVT

Adding 2.6 info

2021-05-27 20:03 UTC, vijayang requested changes

2021-05-27 20:03 UTC, vijayang commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-batching.adoc
> +For B2B and EDI messages that are not time-sensitive, such as invoices and payment remittances, batch messages instead of transmitting transactions to your trading partners individually.
Please rephrase as below:

For EDI messages that are not time-sensitive, such as invoice and payment remittances, you can use the Batch operation to merge multiple individual messages into a single interchange and send to your trading partners.

2021-05-28 14:52 UTC, kbostrom submitted a review, later dismissed
ditto edits edifact-edi/2.3/modules/ROOT/pages/edifact-edi-connector-batching.adoc

2021-05-28 14:52 UTC, kbostrom commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-batching.adoc
> +For EDI messages that are not time-sensitive, such as invoice and payment remittances, you can use the Batch Write operation to merge multiple individual messages into a single interchange to send to
Please duplicate the edits made to the same text in edifact-edi/2.3/modules/ROOT/pages/edifact-edi-connector-batching.adoc (applying the proper connector name, of course).
I will scan to look for anything that is different....

2021-06-08 20:55 UTC, vijayang submitted a review, later dismissed

2021-06-08 21:50 UTC, valkyrie69 approved these changes, later dismissed

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.5/modules/ROOT/pages/x12-edi-connector-control-numbers.adoc
> +Using the Write operation in the Anypoint Connector for X12 EDI Connector (X12 EDI Connector), you can generate control numbers on the generated X12 payload by:
```suggestion
Using the Write operation in Anypoint Connector for X12 EDI Connector (X12 EDI Connector), you can generate control numbers on the generated X12 payload by:
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.5/modules/ROOT/pages/x12-edi-connector-control-numbers.adoc
> +If your organization or your trading partner have must maintain unique interchange, group, or transaction set control numbers across different identifier combinations and document types:
```suggestion
If your organization or your trading partner must maintain unique interchange, group, or transaction set control numbers across different identifier combinations and document types:
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.5/modules/ROOT/pages/x12-edi-connector-control-numbers.adoc
> +* Leverage the control number key configurations (at the configuration level or operation level) to set a key unique to the partner. +
```suggestion
* Leverage the control number key configurations (at the configuration level or operation level) to set a key that is unique to the partner. +
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.5/modules/ROOT/pages/x12-edi-connector-control-numbers.adoc
> +If you must generate the control numbers and use them on the EDI payload, you can set the parameter `Use supplied values` to `true`, and map the control number on the payload in the DataWeave map.
```suggestion
To generate the control numbers and use them on the EDI payload, set the parameter `Use supplied values` to `true`, and map the control number on the payload in the DataWeave map.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/index.adoc
> +* Sets up your Outbound transactions.
```suggestion
* Setting up your Outbound transactions.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/index.adoc
> +* Sets up your Inbound transactions.
```suggestion
* Setting up your Inbound transactions.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/index.adoc
> +* Use this for setting up your Partner Manager content storage.
The lead-in sentence to this bullet point is:
[Anypoint Exchange Templates] provide starting points for Studio projects such as:

So this wording should probably be modified somehow.

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-batching.adoc
> +You implement a batch involves two stages:
```suggestion
Implementing a batch involves two stages:
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-batching.adoc
> +This enables sending the accumulated X12 as a batch later. The batch is created using control numbers that are not used in the final batch sent to the trading partner, for example, `<x12:write doc:na
```suggestion
This enables sending the accumulated X12 as a batch at a later time. The batch is created using control numbers that are not used in the final batch that is sent to the trading partner, for example, `<x12:write doc:name="Create a single X12 810 Invoice Txn" doc:id="767e1321-044d-4ed4-95ba-6ddc78efb0b4" config-ref="X12_EDI_Write_810" interchangeNumberKey="MYTHICAL-NTOETAIL-ISA-TMP" groupNumberKey="MYTHICAL-NTOETAIL-GS-TMP"/>`.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-config-topics.adoc
> +. Switch to the XML view by clicking Configuration XML
```suggestion
. Switch to the XML view by clicking *Configuration XML*.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-control-numbers.adoc
> +If your organization or your trading partner have must maintain unique interchange, group, or transaction set control numbers across different identifier combinations and document types:
```suggestion
If your organization or your trading partner must maintain unique interchange, group, or transaction set control numbers across different identifier combinations and document types:
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-control-numbers.adoc
> +If you must generate the control numbers and use them on the EDI payload, you can set the parameter `Use supplied values` to `true`, and map the control number on the payload in the DataWeave map.
```suggestion
To generate the control numbers and use them on the EDI payload, set the parameter `Use supplied values` to `true`, and map the control number on the payload in the DataWeave map.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-hipaa.adoc
> +* Select one or more HIPAA schemas to be used.
```suggestion
* Select one or more HIPAA schemas to use.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-hipaa.adoc
> +There are two types of validations to use for integrity testing.
```suggestion
There are two types of validations to use for integrity testing:
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-hipaa.adoc
> +Testing of the EDI file for valid segments, segment order, element attributes, testing for numeric values in numeric data elements, validation of X12 or NCPDP syntax, and compliance with X12 and NCPD
```suggestion
Tests the EDI file for valid segments, segment order, element attributes, as well as testing for numeric values in numeric data elements, validation of X12 or NCPDP syntax, and compliance with X12 and NCPDP rules.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-hipaa.adoc
> +Testing for HIPAA Implementation Guide-specific syntax requirements, such as limits on repeat counts, used and not used qualifiers, codes, elements, and segments. Also included in this type is testin
```suggestion
Tests for HIPAA Implementation Guide-specific syntax requirements, such as limits on repeat counts, used and not used qualifiers, codes, elements, and segments. Also included in this type is testing for HIPAA-required or intra-segment situational data elements, testing for non-medical code sets as laid out in the WEDI SNIP implementation guide, and values and codes noted in the WEDI SNIP implementation guide using an X12 code list or table.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-reference.adoc
> +| Expiration Policy a| ExpirationPolicy |  Configures the minimum amount of time that a dynamic configuration instance can remain idle before the runtime considers it eligible for expiration. This do
```suggestion
| Expiration Policy a| ExpirationPolicy |  Configures the minimum amount of time that a dynamic configuration instance can remain idle before Mule considers it eligible for expiration. |  |
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-reference.adoc
> +** UNRESTRICTED | Characters allowed in string data. Invalid characters are replaced by the substitution character, if used, or rejected as errors if no substitution character is set or enabled for r
```suggestion
** UNRESTRICTED | Characters allowed in string data. Invalid characters are replaced by the substitution character, if used, or rejected as errors if no substitution character is set or enabled for receive messages in parser options. Either way the invalid characters are logged, and receive messages are reported in 997 functional acknowledgments. |  EXTENDED |
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-reference.adoc
> +** UNRESTRICTED | Characters allowed in string data. Invalid characters are replaced by the substitution character, if used, or rejected as errors if no substitution character is set or enabled for r
?

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-connector-understand-edi-schema.adoc
> +You can define your own schemas from scratch, or copy and edit a base X12 schema definition to suit your data as shown in the xref:x12-edi-schema-language-reference.adoc[EDI Schema Language Reference
```suggestion
You can define your own custom schemas, or copy and edit a base X12 schema definition to suit your data as shown in the xref:x12-edi-schema-language-reference.adoc[EDI Schema Language Reference].
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-schema-language-reference.adoc
> +* the EDI standard
I think all bullet points should be init capped.

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-schema-language-reference.adoc
> +The ESL structures shown here defines all simple key-value pairs before any lists that are part of the same definition.
```suggestion
The ESL structures shown here define all simple key-value pairs before any lists that are part of the same definition.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-schema-language-reference.adoc
> +The lists of segments for each section of the structure use the same form. Each item in the list is either a segment reference or a group definition. Segment references use a compact YAML syntax: the
```suggestion
The lists of segments for each section of the structure use the same form. Each item in the list is either a segment reference or a group definition. Segment references use a compact YAML syntax; the values for each are shown as comma-separated key-value pairs enclosed in curly braces.
```

2021-06-08 21:50 UTC, valkyrie69 commented on x12-edi/2.6/modules/ROOT/pages/x12-edi-schema-language-reference.adoc
> +The values list references elements and composites by ID, and use a compact YAML syntax: the values for each are shown as comma-separated key-value pairs enclosed in curly braces.
I'm not sure about using a colon that way. I commented previously, but disregard if you think it's fine. And it's really not important right now.

2021-06-08 21:59 UTC, valkyrie69 submitted a review, later dismissed

2021-06-08 22:13 UTC, valkyrie69 approved these changes

2021-06-08 22:13 UTC, merged