DOCS-11909-ftps-troubleshooting-guide-kt
mulesoft/docs-connectors pull request #1607
Opened 2021-08-27 21:02 UTC by kevintroller

- FTPS Troubleshooting guide
- Adding Troubleshooting SDK Components xref link
- Wait merging of https://github.com/mulesoft/docs-mule-sdk/pull/163/files to merge current PR.

2021-12-29 21:05 UTC, giss-ignacio requested changes

2021-12-29 21:05 UTC, giss-ignacio commented on ftps/1.6/modules/ROOT/pages/ftps-troubleshooting.adoc
> +    <AsyncLogger name=“com.jcraft.jsch” level=“DEBUG”/>
jsch library is not used on the FTPS connector. Instead, apache.commons.net is used through its dependency on the FTP connector
`<AsyncLogger name=“org.mule.extension.ftp” level=“TRACE”/>`
`<AsyncLogger name=“org.apache.commons.net” level=“DEBUG”/>`
can be added to the logging.

2021-12-30 12:39 UTC, giss-ignacio requested changes

2021-12-30 12:39 UTC, giss-ignacio commented on ftps/1.6/modules/ROOT/pages/ftps-troubleshooting.adoc
> +* xref:sftp-documentation.adoc[SFTP Connector Reference]
`* xref:ftps-documentation.adoc[FTPS Connector Reference]`

2021-12-30 12:42 UTC, giss-ignacio commented on ftps/1.6/modules/ROOT/pages/ftps-troubleshooting.adoc
> +* xref:sftp-documentation.adoc[SFTP Connector Reference]
Please remove the link to the SFTP Connector Reference.

2022-01-12 15:56 UTC, tasmoore commented on ftps/1.6/modules/ROOT/pages/ftps-troubleshooting.adoc
> +* Try to minimize or remove unnecessary DataWeave data transformations (you could even use hard coded data) to minimize app's complexity and determine whether the issue is with the interaction betwee
Change "minimize app's complexity" to "minimize the app's complexity"

2022-01-12 15:57 UTC, tasmoore commented on ftps/1.6/modules/ROOT/pages/ftps-troubleshooting.adoc
> +To get further information about enabling verbose logging for SDK components in your Mule application, see the xref:mule-sdk::troubleshooting.adoc[troubleshoot SDK components] documentation.
Consider changing "To get further information about" to "For additional information about"

2022-01-12 15:58 UTC, tasmoore commented on ftps/1.6/modules/ROOT/pages/ftps-troubleshooting.adoc
> +To troubleshoot Anypoint Connector for FTPs (FTPS Connector), become familiar with the information about troubleshooting Mule application issues
Add a period at the end.

2022-01-12 16:00 UTC, tasmoore submitted a review, later dismissed

2022-01-12 17:12 UTC, tasmoore commented on ftps/1.6/modules/ROOT/pages/ftps-troubleshooting.adoc
> +* Try to replicate the issue using a FTPS client, for example, Cyberduck or Filezilla. If the issue also occurs with these clients, then it is likely that the issue is not related to the Mule app.
Change "a FTPS client" to "an FTPS client"

2022-01-12 17:13 UTC, tasmoore submitted a review, later dismissed

2022-01-12 18:45 UTC, tasmoore approved these changes

2022-01-13 13:18 UTC, giss-ignacio approved these changes

2022-01-13 13:55 UTC, merged