DOCS-11909-file-troubleshooting-guide-kt
mulesoft/docs-connectors pull request #1608
Opened 2021-08-27 21:06 UTC by kevintroller

- File Connector Troubleshooting guide
- Adding Troubleshooting SDK Components xref link
- Wait merging of https://github.com/mulesoft/docs-mule-sdk/pull/163/files to merge current PR.

2021-12-29 21:07 UTC, giss-ignacio requested changes

2021-12-29 21:07 UTC, giss-ignacio commented on file/1.3/modules/ROOT/pages/file-troubleshooting.adoc
> +    <AsyncLogger name=“com.jcraft.jsch” level=“DEBUG”/>
This connector does not use this library. This line can be removed.

2021-12-30 12:36 UTC, giss-ignacio requested changes

2021-12-30 12:36 UTC, giss-ignacio commented on file/1.3/modules/ROOT/pages/file-troubleshooting.adoc
> +Sometimes you are not sure why the application is failing and you require a better understanding of what is going on in the app's interaction with the File server.
I think it would be File System instead of File Server.

2021-12-30 12:36 UTC, giss-ignacio commented on file/1.3/modules/ROOT/pages/file-troubleshooting.adoc
> +* Try to minimize or remove unnecessary DataWeave data transformations (you could even use hard coded data) to minimize app's complexity and determine whether the issue is with the interaction betwee
I think it would be File System instead of File Server.

2021-12-30 12:36 UTC, giss-ignacio commented on file/1.3/modules/ROOT/pages/file-troubleshooting.adoc
> +* xref:sftp-documentation.adoc[SFTP Connector Reference]
`xref:file-documentation.adoc[File Connector Reference]`

2021-12-30 12:42 UTC, giss-ignacio commented on file/1.3/modules/ROOT/pages/file-troubleshooting.adoc
> +* xref:sftp-documentation.adoc[SFTP Connector Reference]
Please remove the link to the SFTP Connector Reference.

2022-01-12 15:48 UTC, tasmoore commented on file/1.3/modules/ROOT/pages/file-troubleshooting.adoc
> +To troubleshoot Anypoint Connector for File (File Connector), become familiar with the information about troubleshooting Mule application issues
Add a period at the end.

2022-01-12 15:48 UTC, tasmoore commented on file/1.3/modules/ROOT/pages/file-troubleshooting.adoc
> +* Try to replicate the issue using an File client, for example, Cyberduck or Filezilla. If the issue also occurs with these clients, then it is likely that the issue is not related to the Mule app.
Change "an File client" to "a File client"

2022-01-12 15:51 UTC, tasmoore commented on file/1.3/modules/ROOT/pages/file-troubleshooting.adoc
> +* Try to minimize or remove unnecessary DataWeave data transformations (you could even use hard coded data) to minimize app's complexity and determine whether the issue is with the interaction betwee
Change "minimize app's complexity" to "minimize the app's complexity"

2022-01-12 15:52 UTC, tasmoore commented on file/1.3/modules/ROOT/pages/file-troubleshooting.adoc
> +To get further information about enabling verbose logging for SDK components in your Mule application, see the xref:mule-sdk::troubleshooting.adoc[troubleshoot SDK components] documentation.
Consider changing "To get further information about" to "For additional information about"

2022-01-12 15:52 UTC, tasmoore submitted a review, later dismissed

2022-01-12 17:07 UTC, tasmoore approved these changes

2022-01-13 13:18 UTC, giss-ignacio approved these changes

2022-01-13 13:54 UTC, merged