DOCS-12263 Kafka 4.6
mulesoft/docs-connectors pull request #1659
Opened 2021-10-11 22:46 UTC by sathya0

2021-10-13 05:26 UTC, GeorgeTrifSV commented on kafka/4.6/modules/ROOT/pages/kafka-connector-reference.adoc
> +| TLS Configuration a| <<Tls>> |  Defines a TLS configuration, used by both clients and server sides to secure the communication for the Mule app. The connector automatically sets the `security.proto
Add 

> token

to the end list

2021-10-13 05:26 UTC, GeorgeTrifSV commented on kafka/4.6/modules/ROOT/pages/kafka-connector-reference.adoc
> +| TLS Configuration a| <<Tls>> |  Defines a TLS configuration, used by both clients and server sides to secure the communication for the Mule app. The connector automatically sets the `security.proto
(Kerberos/SCRAM/PLAIN/TOKEN)

2021-10-13 05:26 UTC, GeorgeTrifSV commented on kafka/4.6/modules/ROOT/pages/kafka-connector-reference.adoc
> +| TLS Configuration a| <<Tls>> |  Defines a TLS configuration, used by both clients and server sides to secure the communication for the Mule app. The connector automatically sets the `security.proto
same here

2021-10-14 06:18 UTC, GeorgeTrifSV submitted a review, later dismissed
✅

2021-10-14 17:06 UTC, dhirsch1 commented on kafka/4.6/modules/ROOT/pages/kafka-connector-reference.adoc
> +
with > to
"with" is ambiguous here because it also mean that the delegation tokens use the Kafka cluster for authentication.

Ditto for the other configuration.

2021-10-14 17:13 UTC, dhirsch1 commented on kafka/4.6/modules/ROOT/pages/kafka-connector-reference.adoc
> +| Buffer size a| Number |  Total bytes of memory the producer can use to buffer records waiting to be sent to the server. If records are sent faster than they can be delivered to the server, the prod
Use backticks for 3554432.

2021-10-14 17:14 UTC, dhirsch1 commented on kafka/4.6/modules/ROOT/pages/kafka-connector-reference.adoc
> +| Retries amount a| Number |  Setting a value greater than zero causes the client to resend any record whose send fails with a potentially transient error. This retry is no different than if the clie
will be > are

2021-10-14 17:14 UTC, dhirsch1 commented on kafka/4.6/modules/ROOT/pages/kafka-connector-reference.adoc
> +* `default`
These entries should batch what is in the Enumeration column

2021-10-14 17:16 UTC, dhirsch1 requested changes
Just a few minor things. At some point, whoever works on this reference should break out some of the very large paragraphs to make the text easier to read.

2021-10-14 18:17 UTC, dhirsch1 approved these changes

2021-10-19 15:36 UTC, merged