DOCS-12430 SAP Successfactors 4.1
mulesoft/docs-connectors pull request #1678
Opened 2021-10-26 23:40 UTC by sathya0

2021-10-27 07:37 UTC, GeorgeTrifSV requested changes

2021-10-27 07:37 UTC, GeorgeTrifSV commented on sap-successfactors/4.1/modules/ROOT/pages/sap-successfactors-connector-reference.adoc
> +** CURSOR
Can you leave a note that:

> Snapshot Pagination does not support `$top` and `$skip`

> Cursor Pagination does not support `$orderby`

2021-10-28 06:26 UTC, GeorgeTrifSV submitted a review, later dismissed

2021-11-02 17:00 UTC, dhirsch1 commented on sap-successfactors/4.1/modules/ROOT/pages/sap-successfactors-connector-upgrade-migrate.adoc
> +
Do you want to include an update for v4.1?

2021-11-02 17:02 UTC, dhirsch1 commented on sap-successfactors/4.1/modules/ROOT/pages/sap-successfactors-connector-xml-maven.adoc
> += SAP SuccessFactors Connector XML and Maven Support - Mule 4
```suggestion
= SAP SuccessFactors Connector 4.1 XML and Maven Support - Mule 4
```

2021-11-02 17:06 UTC, dhirsch1 commented on sap-successfactors/4.1/modules/ROOT/pages/sap-successfactors-connector-upgrade-migrate.adoc
> += Upgrade SAP SuccessFactors Connector to Version 4.0 - Mule 4
I want to discuss how to deal with update topics like this one at a connector meeting. We should probably change 4.0 to 4.x and add the new functionality for the minor release but don't do anything now.

2021-11-02 17:07 UTC, dhirsch1 commented on sap-successfactors/4.1/modules/ROOT/pages/sap-successfactors-connector-config-topics.adoc
> += SAP SuccessFactors - Additional Configuration Information - Mule 4
```suggestion
= SAP SuccessFactors 4.1 - Additional Configuration Information - Mule 4
```

2021-11-02 17:08 UTC, dhirsch1 submitted a review, later dismissed

2021-11-02 18:08 UTC, dhirsch1 approved these changes

2021-11-02 21:54 UTC, merged