W-10588485-ftps-studio-configuration-kt
mulesoft/docs-connectors pull request #1799
Opened 2022-02-10 19:43 UTC by kevintroller

Adding FTPS Connector Studio Configuration page and reorganizing index

2022-02-14 19:20 UTC, kbostrom approved these changes
CE

2022-02-14 19:20 UTC, kbostrom commented on ftps/1.6/modules/ROOT/pages/ftps-studio-configuration.adoc
> +Add FTPS Connector to your Mule project to automatically populate the XML code with the connector's namespace and schema location and to add the required dependencies to the project's `pom.xml` file:
```suggestion
Add Anypoint Connector for FTPS (FTPS Connector) to your Mule project to automatically populate the XML code with the connector's namespace and schema location and to add the required dependencies to the project's `pom.xml` file:
```

2022-02-14 19:20 UTC, kbostrom commented on ftps/1.6/modules/ROOT/pages/ftps-studio-configuration.adoc
> +. Set *Username* and *Password*.
Lines 93-96 should be substeps, yes?

2022-02-14 19:20 UTC, kbostrom commented on ftps/1.6/modules/ROOT/pages/ftps-studio-configuration.adoc
> +In the *Configuration XML* editor, the `ftps=mode`, `ftps-explicit-mode`, and `protSetting` configurations look like this:
Yay! :-)

2022-02-14 19:20 UTC, kbostrom commented on ftps/1.6/modules/ROOT/pages/ftps-studio-configuration.adoc
> +To reuse sessions using FTPS you must disable the Extended Master Secret extension for compatibility (JDK-8192045), which by default is set to `true`. The extension protects users from vulnerabilitie
Not to sure about using "contradicts" in this context.... How about this?
```suggestion
To reuse sessions using FTPS you must disable the Extended Master Secret extension for compatibility (JDK-8192045), which by default is set to `true`. The extension protects users from vulnerabilities by using the same session on different groups of clients and servers, instead of using the same session for control and data connections. With the Extended Master Secret extension activated, session reuse is possible only by endpoint verification, which is implemented for HTTPS and LDAP only.
```

2022-02-14 19:20 UTC, kbostrom commented on ftps/1.6/modules/ROOT/pages/ftps-studio-configuration.adoc
> +. In the *VM arguments* box, add the following argument to the JVM execution:
to the execution or to the execution...command? syntax?

2022-02-14 19:20 UTC, kbostrom commented on ftps/1.6/modules/ROOT/pages/ftps-studio-configuration.adoc
> +To disable the Extended Master Secret extension when working in a standalone Mule environment, add the following argument to the JVM execution:
ditto re. "execution"

2022-02-14 19:20 UTC, kbostrom commented on ftps/1.6/modules/ROOT/pages/index.adoc
> +Anypoint Connector for FTPS (FTPS Connector) connects to FTP servers the same way as the xref:ftp-connector::index.adoc[FTP Connector] but adds support for xref:mule-runtime::tls-configuration.adoc[T
```suggestion
Anypoint Connector for FTPS (FTPS Connector) connects to FTP servers the same way as xref:ftp-connector::index.adoc[Anypoint Connector for FTP (FTP Connector)] but adds support for xref:mule-runtime::tls-configuration.adoc[Transport Layer Security (TLS)].
```

2022-02-15 15:20 UTC, dhirsch1 commented on ftps/1.6/modules/ROOT/pages/ftps-studio-configuration.adoc
> +You can use Transport Layer Security (TLS) and configure FTPS by providing a key store with your certificate. You can also enable 2-way authentication by providing a trust store. For more information
trust store > truststore per our style

2022-02-15 15:23 UTC, dhirsch1 requested changes
One minor change

2022-02-15 16:21 UTC, dhirsch1 approved these changes

2022-02-16 17:45 UTC, merged