W-10731885 Google BigQuery 1.0
mulesoft/docs-connectors pull request #1825
Opened 2022-03-01 17:54 UTC by sathya0

2022-03-18 21:28 UTC, tomastoloza requested changes
Some comments regarding operation names.
I will be updating the suggestions in our code as well to avoid any discrepancies.

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +|Project Id | `attributes.queryParams.projectId`
Remove projectId since it is no longer a parameter for operations

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +|Project Id | `attributes.queryParams.projectId`
Remove projectId since it is no longer a parameter for operations

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +|Project Id | `attributes.queryParams.projectId`
Remove projectId since it is no longer a parameter for operations

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +|Project Id | `attributes.queryParams.projectId`
Remove projectId since it is no longer a parameter for operations

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +== Get a Job Result
```suggestion
== Get a Query Result
```

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +[[get-job-result]]
```suggestion
[[get-query-result]]
```

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +* <<get-job-result>>
```suggestion
* <<get-query-result>>
```
I found out there are references to **Get Query Result** as **Get Job Result**, I will be updating this into our demos/readme/etc to match the suggestions here

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +image::get-job-result.png[Studio Flow for the Get Query Results operation]
I think we should rename this file to get-query-result

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +|Project Id | `attributes.queryParams.projectId`
Remove projectId since it is no longer a parameter for operations

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +|Project Id | `attributes.queryParams.projectId`
Remove projectId since it is no longer a parameter for operations

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +|Project Id | `attributes.queryParams.projectId`
Remove projectId since it is no longer a parameter for operations

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +	<flow name="getJobResultFlow">
```suggestion
	<flow name="getJobQueryFlow">
```
I will update these suggestions in our code as well

2022-03-18 21:28 UTC, tomastoloza commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-examples.adoc
> +		<bigquery:get-query-results doc:name="Get Job Result Paged" config-ref="BigQuery__Configuration" maxResults="25" jobId="#[attributes.queryParams.jobId]">
```suggestion
		<bigquery:get-query-results doc:name="Get Query Result Paged" config-ref="BigQuery__Configuration" maxResults="25" jobId="#[attributes.queryParams.jobId]">
```

2022-03-23 13:30 UTC, tomastoloza approved these changes, later dismissed
Looks good, thank you!

2022-03-25 17:40 UTC, tasmoore commented on google-bigquery/1.0/modules/ROOT/pages/google-bigquery-connector-studio.adoc
> +The first item shows where to specify that the connector uses OAuth2 authentication. The second item shows the *General tab*, which contains fields related to OAuth2 authentication.
Should "tab" be unbolded here?

2022-03-25 17:46 UTC, tasmoore submitted a review, later dismissed

2022-03-25 18:01 UTC, tasmoore approved these changes

2022-03-25 18:01 UTC, merged