W-10822513-email-connector-1.6-kt
mulesoft/docs-connectors pull request #1831
Opened 2022-03-10 20:49 UTC by kevintroller

Documentation for Email Connector 1.6
- New **Move to folder** operation example.

2022-03-10 21:01 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +Anypoint Connector for Email (Email Connector) provides the *Move to folder* operation that enables you to move messages to folders for IMAP and IMAPS connection providers. The operation main feature
```suggestion
Anypoint Connector for Email (Email Connector) provides the *Move to folder* operation that enables you to move messages to folders for IMAP and IMAPS connection providers. The operation's main features include:
```

2022-03-10 21:01 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +* *Host* `outlook.office365.com`
```suggestion
* *Host*: `outlook.office365.com`
```

2022-03-10 21:01 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +* *Port* `993`
```suggestion
* *Port*: `993`
```

2022-03-10 21:01 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +* *User* `test123@outlook.com`
```suggestion
* *User*: `test123@outlook.com`
```

2022-03-10 21:01 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +* *Password* `testpassword`
```suggestion
* *Password*: `testpassword`
```

2022-03-10 21:01 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +The following example illustrates how to move a received message from one folder to another folder. A *On New Email - IMAP* source initiates the flow, and then the *Mark as read* operation reads the
```suggestion
The following example illustrates how to move a received message from one folder to another folder. An *On New Email - IMAP* source initiates the flow, and then the *Mark as read* operation reads the received email in the `INBOX` folder. Subsequently, the *Move to folder* operation moves the email to the `TARGET` folder:
```

2022-03-10 21:01 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +. Drag a *Move to folder* opertion to the right of the *Mark as read* operation.
```suggestion
. Drag a *Move to folder* operation to the right of the *Mark as read* operation.
```

2022-03-10 21:01 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +The following example illustrates how to move a received message from one folder to another, if the target folder does not exist, the folder is then created. A *On New Email - IMAP* source initiates
```suggestion
The following example illustrates how to move a received message from one folder to another, if the target folder does not exist, the folder is then created. An *On New Email - IMAP* source initiates the flow, and then the *Mark as read* operation reads the received email in the `INBOX` folder. Subsequently, the *Move to folder* operation moves the email to the `TARGET` folder. If that folder does not exist, it is created automatically.
```

2022-03-10 21:01 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +. Drag a *Move to folder* opertion to the right of the *Mark as read* operation.
```suggestion
. Drag a *Move to folder* operation to the right of the *Mark as read* operation.
```

2022-03-11 16:14 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-documentation.adoc
> +* <<reconnect-forever>> |  Configures a forever reconnection strategy by which the connector source or operation attempts to reconnect at a specified frequency for as long as the Mule app runs.. |  |
```suggestion
* <<reconnect-forever>> |  Configures a forever reconnection strategy by which the connector source or operation attempts to reconnect at a specified frequency for as long as the Mule app runs. |  |
```

2022-03-11 16:14 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-documentation.adoc
> +* <<reconnect-forever>> |  Configures a forever reconnection strategy by which the connector source or operation attempts to reconnect at a specified frequency for as long as the Mule app runs.. |  |
```suggestion
* <<reconnect-forever>> |  Configures a forever reconnection strategy by which the connector source or operation attempts to reconnect at a specified frequency for as long as the Mule app runs. |  |
```

2022-03-11 16:14 UTC, sathya0 commented on email/1.6/modules/ROOT/pages/email-documentation.adoc
> +* <<reconnect-forever>> |  Configures a forever reconnection strategy by which the connector source or operation attempts to reconnect at a specified frequency for as long as the Mule app runs.. |  |
```suggestion
* <<reconnect-forever>> |  Configures a forever reconnection strategy by which the connector source or operation attempts to reconnect at a specified frequency for as long as the Mule app runs. |  |
```

2022-03-11 16:18 UTC, sathya0 submitted a review, later dismissed

2022-03-11 16:57 UTC, nicomz requested changes

2022-03-11 16:57 UTC, nicomz commented on email/1.6/modules/ROOT/pages/index.adoc
> +* Retrieve, delete, and store emails from IMAP mailboxes
Should say
"Retrieve, delete, move and store emails from IMAP mailboxes"

2022-03-11 16:57 UTC, nicomz commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +* *Host*: `outlook.office365.com`
I'd prefer to use another target example server to avoid confusions. We already provide an Office 365 connector.

2022-03-11 16:57 UTC, nicomz commented on email/1.6/modules/ROOT/pages/email-move-folder.adoc
> +                host="outlook.office365.com"
Also the office 365...

2022-03-11 17:47 UTC, nicomz approved these changes

2022-03-14 19:09 UTC, giss-ignacio approved these changes

2022-03-14 20:22 UTC, sathya0 approved these changes

2022-03-14 20:22 UTC, merged