LDAP 3.5 in New Template
mulesoft/docs-connectors pull request #1850
Opened 2022-03-24 15:03 UTC by dhirsch1

2022-03-29 21:06 UTC, kbostrom approved these changes, later dismissed
CE

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> += LDAP Connector Connector 3.5 Examples - Mule 4
```suggestion
= LDAP Connector 3.5 Examples - Mule 4
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +The following examples show how to use LDAP Connector to:
```suggestion
The following example set shows how to use Anypoint Connector for Lightweight Directory Access Protocol Connector (LDAP Connector) to:
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +== Add and Delete Groups and Users from an Organizational Unit
Can you think of a way to balance "delete from" with the implied "add to"?

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +=== Add a User to an Organizational Unit
In all previous texts, we mention "groups" before "user," which I found a little less intuitive than the opposite...and here we document the user part first. So, consider reordering the names of things added and deleted to match the order in which we document the actual tasks.

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +. Add these properties to the `mule-artifact.properties` file to hold your LDAP credentials, and place the file in the project's `src/main/resources` directory.
```suggestion
. Add these properties to the `mule-artifact.properties` file to hold your LDAP credentials: 
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> ++
```suggestion
. Place the `mule-artifact.properties` file in the project's `src/main/resources` directory.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +. On the Listener properties window, change the display name of the *Listener* source to `HTTP`.
```suggestion
. In the Listener properties window, change the display name of the *Listener* source to `HTTP`.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +. On the Listener properties window, set the *Path* field value to `/`.
```suggestion
. In the Listener properties window, set the *Path* field value to `/`.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +. Configure the global element according to the table below:
```suggestion
. Configure the global element as follows:
```
Avoid "below"

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +|Name|Name of the configuration.|`LDAP_Configuration`
```suggestion
|Name|Name of the configuration|`LDAP_Configuration`
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +|Principal DN|User distinguished name (DN).|`${config.principal.dn}`
```suggestion
|Principal DN|User distinguished name (DN)|`${config.principal.dn}`
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +|Password|User password.|`${config.password}`
```suggestion
|Password|User password|`${config.password}`
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +|URL|URL that connects to the LDAP server.|`${config.url}`
```suggestion
|URL|URL that connects to the LDAP server|`${config.url}`
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +Otherwise, review or correct any incorrect field values and test again.
```suggestion
.. If the connection fails, review and correct any incorrect field values and test again.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +. If the connection is successful, click *OK* to save the configuration.
```suggestion
. Process connection results as follows:
.. If the connection succeeds, click *OK* to save the configuration.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +. In LDAP Connector properties editor, configure the parameters as follows:
```suggestion
. In the LDAP Connector properties editor, configure the parameters as follows:
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +To add a user to an organizational unit:
```suggestion
To add a user and group to an organizational unit:
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +Now that you have successfully added a user and group to an organizational unit, try to delete them using LDAP Connector:
```suggestion
After you successfully add a user and group to an organizational unit, delete them using LDAP Connector:
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> ++
correct formatting?

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +=== XML for the Adding and Deleting Groups and Users from an Organizational Unit Example
```suggestion
=== XML for the Example
```
Avoids the order issue and the to/from issue.

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +Paste this code into your XML Editor to quickly load the flow for this example use case into your Mule app:
```suggestion
Paste this code into your XML Editor to quickly load the flow for this example to your Mule app:
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> ++
ditto prev. edit suggestion to split into two separate steps

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +. On the *On Modified Objects* configuration screen, optionally change the value of the *Display Name* field.
```suggestion
. If you want to customize the display name, change the value of the *Display Name* field.
```
Pattern I'd like to see followed for optional steps, per style ref.

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +. In the *Connector configuration* field, either select an existing global element or click the plus sign (*+*) next to configure a new global element.
Is "configure a new global element" a UI label, or should this be something like:
```suggestion
. In the *Connector configuration* field, either select an existing global element or click the plus sign (*+*) to configure a new global element.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +. On the *General* tab, specify the principal distinguished name (DN) for the connection, authentication, and the configuration URL.
Should this be...:
```suggestion
. On the *General* tab, specify the principal distinguished name (DN) for both the connection and for authentication, and specify the configuration URL.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +. On the *Advanced* tab, reconnection information, including a reconnection strategy.
```suggestion
. On the *Advanced* tab, specify reconnection information, including a reconnection strategy.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +. On the *On Modified Objects* configuration screen, specify a value for the *Base DN* field.
```suggestion
. In the *On Modified Objects* configuration screen, specify a value for the *Base DN* field.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +. In the *General* tab, in *Connection*, select the connection type, and then complete the associated
```suggestion
. In the *General* tab, in *Connection*, select the connection type and then complete the associated
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +Connect to SLS using port.
Is this a step? Is something missing?

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +. Ensure that the native LDAP pooling functionality is turned off. For example if using JNDI, do not use attributes such as `com.sun.jndi.ldap.connect.pool=true`, which cause problems when using TLS.
Is the example necessary? Makes the step long.

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +Connect to TLS using port 389. Use `ldap` instead of of `ldaps` in the associated URL.
```suggestion
Connect to TLS using port 389, using `ldap` instead of of `ldaps` in the associated URL.
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +For an example of configuring a TLS connection, see xref:ldap-connector-examples.adoc#set-up-common-truststore[Set up a Common Truststore].
```suggestion
For an example of configuring a TLS connection, see xref:ldap-connector-examples.adoc#set-up-common-truststore[Set Up a Common Truststore].
```

2022-03-29 21:06 UTC, kbostrom commented on ldap/3.5/modules/ROOT/pages/ldap-connector-xml-maven.adoc
> +* If you add the connector in Studio, Studio automatically populates the XML code with the connector's namespace and schema location and it also adds a dependency to the `pom.xml` file.
```suggestion
* If you add the connector in Studio, Studio automatically populates the XML code with the connector's namespace and schema location and adds a dependency to the `pom.xml` file.
```

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/index.adoc
> +:page-aliases: connectors::ldap/ldap-connector.adoc
just checking if this page alias was supposed to be added?

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/index.adoc
> +Many LDAP servers are included in free-use open source projects and packages. The particulars of installing, running and configuring LDAP servers fall outside the scope of this document.
```suggestion
Many LDAP servers are included in free-use open source projects and packages. The particulars of installing, running, and configuring LDAP servers fall outside the scope of this document.
```

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> += See Also
```suggestion
== See Also
```

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +https://help.mulesoft.com[MuleSoft Help Center]
```suggestion
* https://help.mulesoft.com[MuleSoft Help Center]
```

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +
not necessary, but maybe add a section for the final XML for this example?

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> += Use Studio to Configure LDAP Connector 3.5 - Mule 4
```suggestion
= Using Studio to Configure LDAP Connector 3.5 - Mule 4
```

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +. Ensure that the native LDAP pooling functionality is turned off. For example if using JNDI, do not use attributes such as `com.sun.jndi.ldap.connect.pool=true`, which cause problems when using TLS.
```suggestion
. Ensure that the native LDAP pooling functionality is turned off. For example if using JNDI, do not use attributes such as `com.sun.jndi.ldap.connect.pool=true`, which causes problems when using TLS.
```

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +Connect to TLS using port 389, using `ldap` instead of of `ldaps` in the associated URL.
```suggestion
Connect to TLS using port 389, using `ldap` instead of `ldaps` in the associated URL.
```

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +After you configure a global element for LDAP Connector, configure the the other required fields for the connector. The required fields vary depending on which connector operation you use.
```suggestion
After you configure a global element for LDAP Connector, configure the other required fields for the connector. The required fields vary depending on which connector operation you use.
```

2022-04-07 15:47 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-xml-maven.adoc
> +. In Exchange, search for `connector-template-files`.
```suggestion
. In Exchange, search for `ldap`.
```

2022-04-07 18:13 UTC, javiermule requested changes

2022-04-07 18:13 UTC, javiermule commented on ldap/3.5/modules/ROOT/pages/ldap-connector-reference.adoc
> -Release Notes: xref:release-notes::connector/ldap-connector-release-notes-mule-4.adoc[LDAP Connector Release Notes]
Should the release notes reference be removed from here?

2022-04-07 18:13 UTC, javiermule commented on ldap/3.5/modules/ROOT/pages/ldap-connector-xml-maven.adoc
> += LDAP Connector 3.5 - XML and Maven Support - Mule 4
Is there a way/does it make sense, to have a template of this generic information?

2022-04-07 18:13 UTC, javiermule commented on ldap/3.5/modules/ROOT/pages/ldap-connector-use-studio.adoc
> +Connect to SLS using port 636.
SLS -> SSL

2022-04-07 19:36 UTC, dhirsch1 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-reference.adoc
> -Release Notes: xref:release-notes::connector/ldap-connector-release-notes-mule-4.adoc[LDAP Connector Release Notes]
Yes, they were removed.

2022-04-11 14:02 UTC, dhirsch1 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-xml-maven.adoc
> += LDAP Connector 3.5 - XML and Maven Support - Mule 4
We have a template that we use for this type of information.

2022-04-11 19:58 UTC, javiermule approved these changes, later dismissed

2022-04-11 20:23 UTC, sathya0 commented on ldap/3.5/modules/ROOT/pages/ldap-connector-examples.adoc
> +<<<<<<< Updated upstream
May need to delete lines 154, 156, 157, 158

2022-04-11 21:21 UTC, sathya0 approved these changes

2022-04-12 12:52 UTC, dhirsch1 commented
__

2022-04-12 12:52 UTC, merged