Updating the output application/ type
mulesoft/docs-connectors pull request #195
Opened 2019-05-09 23:15 UTC by vishnusamavedula

We recently did a workshop using Twilio connector. Upon following the instructions from MuleSoft's documentation, I constantly got errors while compiling a simple flow to send SMS. Upon looking at the Twilio Programmable SMS dashboard (Twilio Dev Account), the cURL request accepts '--data-urlencode' only for accepting To, From and Body.
Upon the changing the transform to output application/x-www-form-urlencoded, I was able to make the sms functionality work without any issues.

2019-05-10 19:42 UTC, wwarner-salesforce commented
@vishnusamavedula , thank you!

@adam-lipka , could you please review?

2019-05-14 11:46 UTC, adam-lipka requested changes
Please try to use `application/java` instead of `application/x-www-form-urlencoded`and let me know if it works for you. If it does, please update the PR.

2019-05-14 16:42 UTC, wwarner-salesforce commented
Sounds good. I will leave this PR untouched until @vishnusamavedula replies or updates.

2019-05-16 23:40 UTC, vishnusamavedula commented
Yep, application/java worked fine. I tried few simple use cases with application/json, and they seem to be working as well. So not sure about the error, as I am unable to reproduce it again.

2019-05-17 00:00 UTC, wwarner-salesforce commented
@vishnusamavedula thank you!

@adam-lipka your call. Is it better for the docs to say `java` or remain as `json`?

2019-05-17 00:13 UTC, vishnusamavedula commented
Lets change it to java in that case, just to be safe. I will continue to test json payloads with Twilio connector.

2019-05-21 12:59 UTC, adam-lipka commented
@wwarner-salesforce It should be `java`. 

@vishnusamavedula feel free to update you PR. Thanks!

2019-05-21 17:02 UTC, wwarner-salesforce approved these changes

2019-05-21 17:03 UTC, merged

2019-05-21 17:03 UTC, wwarner-salesforce commented
Thank you very much, @vishnusamavedula and @adam-lipka !

2019-06-05 12:44 UTC, adam-lipka reviewed
This look fine to me. Thanks!