Fix DB Examples
mulesoft/docs-connectors pull request #205
Opened 2019-05-21 21:11 UTC by mcherem

Fix DB Examples

2019-05-22 12:18 UTC, estebanwasinger requested changes

2019-05-22 12:18 UTC, estebanwasinger commented on modules/ROOT/pages/db/db-connector-sp.adoc
> +Create a stored procedures that allows the input, output, and input-output of payload parameters.
This doesn't create stored procedures, invokes stored procedures.
Doesn't exist such thing as "payload parameters"

2019-05-22 12:20 UTC, estebanwasinger requested changes
This PR doesn't fix any of the issues that the documentation have:
As a list of things that I think should be fixed:
1) The layout, one big example is not ok, should be split 
2) Explain what is an input parameter, an output parameter, and in-out parameter
2b) when I should use each of those
3) missing real world examples

2019-07-24 22:36 UTC, closed without merging

2019-07-24 22:36 UTC, mcherem commented
This has been superseded by a PR from the Dev team.