DOCS-3416: Add information about processing output in SQL queries.
mulesoft/docs-connectors pull request #210
Opened 2019-05-23 17:19 UTC by SebaElizalde

Added a section on how to process the query output, datasense support for it and added a link to the for each scope.

2019-06-05 20:34 UTC, Bardammu commented on modules/ROOT/pages/db/db-connector-query.adoc
> +parts of the query itself. Examples of use cases for this are queries that need to hit online
The example is useless I think

2019-06-06 20:32 UTC, estebanwasinger requested changes

2019-06-06 20:32 UTC, estebanwasinger commented on modules/ROOT/pages/db/db-connector-query.adoc
> +The output of this query will be saved in the payload as an collection (array) of objects. With the help
is not saved, is placed or another word.
`collection` -> `array`

2019-07-02 18:06 UTC, estebanwasinger approved these changes

2019-09-30 14:54 UTC, mcherem commented
These comments have been resolved and added to the new templates in the DB doc. Closing this PR.

2019-09-30 14:55 UTC, closed without merging