W-12211144-json-module-2.3.0-kt
mulesoft/docs-connectors pull request #2186
Opened 2022-12-13 13:21 UTC by kevintroller

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2022-12-13 16:00 UTC, tasmoore approved these changes, later dismissed

2022-12-13 17:42 UTC, tasmoore approved these changes, later dismissed

2022-12-13 18:37 UTC, acurci-at-mulesoft requested changes, later dismissed

2022-12-13 18:37 UTC, acurci-at-mulesoft commented on json/2.3/modules/ROOT/pages/json-module-troubleshooting.adoc
> +
Add SCHEMA_INPUT_ERROR

2022-12-13 18:37 UTC, acurci-at-mulesoft commented on json/2.3/modules/ROOT/pages/json-reference.adoc
> +* JSON:INVALID_SCHEMA
Shouldn't you add SCHEMA_INPUT_ERROR to this list?

2023-01-10 15:55 UTC, tasmoore approved these changes

2023-01-10 16:03 UTC, merged