W-16124800-kafka-confluence-configuration-kt
mulesoft/docs-connectors pull request #2631
Opened 2024-07-05 17:35 UTC by kevintroller

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2024-07-08 20:19 UTC, acurci-at-mulesoft requested changes
I think the places that says:
`<kafka:additional-property key="basic.auth.user.info" value="HK6N653LCZCATBEZ:3swV2Zw6jLNODpdwAMqCB6f0+7DNUko/VMZc2w1v7C3APdRZn4PlNz7KH/hxqAdh" />`
should be something like:
`<kafka:additional-property key="basic.auth.user.info" value="*** YOUR CREDENTIALS ***" />`

2024-07-08 20:19 UTC, acurci-at-mulesoft commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +      <kafka:additional-property key="basic.auth.user.info" value="HK6N653LCZCATBEZ:3swV2Zw6jLNODpdwAMqCB6f0+7DNUko/VMZc2w1v7C3APdRZn4PlNz7KH/hxqAdh" />
This value should be an example tests, like: _**** PUT YOUR CREDENTIALS HERE ****_

2024-07-08 20:19 UTC, acurci-at-mulesoft commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +      <kafka:additional-property key="basic.auth.user.info" value="HK6N653LCZCATBEZ:3swV2Zw6jLNODpdwAMqCB6f0+7DNUko/VMZc2w1v7C3APdRZn4PlNz7KH/hxqAdh" />
Idem

2024-07-10 17:44 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +The configuration consits of two parts:
```suggestion
The configuration consists of two parts:
```

2024-07-10 17:45 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +* Configure the Kafka Avro dependency in the POM file of the Mule app.
```suggestion
* Configuring the Confluent Schema Registry in the Kakfa Connector connection using the *Additional Properties* field (either for the *Consumer* or *Producer* operation)
* Configuring the Kafka Avro dependency in the POM file of the Mule app
```
A small rewording to align better with the previous introductory sentence.

2024-07-10 17:47 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +== Configure Kafka Connection
Is this the same as the first part mentioned before? If so, I'd update the title to be more similar: 

== Configure the Confluent Schema Registry in the Kakfa Connector connection

2024-07-10 17:48 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +=== Configuration for Consumer Operation
```suggestion
=== Configure the Consumer Operation
```

2024-07-10 17:48 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +To configure the *Consumer* operation in Anypoint Studio, follow these steps:
```suggestion
To configure the *Consumer* operation in Anypoint Studio:
```

2024-07-10 17:48 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +. Open your Mule project in Anypoint Studio and navigate to the Global Elements tab.
```suggestion
. Open your Mule project in Anypoint Studio and navigate to the *Global Elements* tab.
```

2024-07-10 17:49 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +. In the configuration screen under connection, select *Advanced*.
```suggestion
. In the configuration screen under *connection*, select *Advanced*.
```
Assuming "connection" is a UI element.

2024-07-10 17:50 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +=== Configuration for Producer Operation
```suggestion
=== Configure the Producer Operation
```

2024-07-10 17:53 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +For the *Producer* configuration the difference is to delete `key.deserializer` and `value.deserializer` and replace it with `key.serializer` and `value.serializer`. To configure the *Producer* opera
```suggestion
For the *Producer* operation, you replace `key.deserializer` and `value.deserializer` with `key.serializer` and `value.serializer`. To configure the *Producer* operation in Anypoint Studio:
```

2024-07-10 17:54 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +== Configure POM file in Mule App
```suggestion
== Configure the Kafka Avro dependency in the POM File
```

2024-07-10 17:55 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +In the POM file of the Mule app, you configure the Kafka Avro dependency that contains the class that you use to serialize and deserialize. You must update the `<dependencies>`, `<plugin>`, and `<rep
```suggestion
In the POM file of the Mule app, configure the Kafka Avro dependency that contains the class to use to serialize and deserialize. You must update the `<dependencies>`, `<plugin>`, and `<repository>` sections of the POM file.
```

2024-07-10 17:55 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +=== Configure <dependencies> Section
```suggestion
=== Configure the <dependencies> Section
```

2024-07-10 17:56 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +=== Configure <plugin> Section
```suggestion
=== Configure the <plugin> Section
```

2024-07-10 17:57 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +Then, set the `avro-maven-plugin` plugin. This dependency from the org.apache.avro group is a plugin for Apache Maven that facilitates the handling of Avro schema files in Java projects. The plugin a
```suggestion
Then, set the `avro-maven-plugin` plugin. This dependency from the `org.apache.avro` group is a plugin for Apache Maven that facilitates handling Avro schema files in Java projects. The plugin automatically generates Java classes from Avro schemas (.avsc), protocols (.avpr), and IDL files (.avdl). This process simplifies development by eliminating the need to manually write Java classes that represent Avro schemas, ensuring that the Java code is always synchronized with the Avro schemas.
```

2024-07-10 17:59 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +== Configure <repository> Section
```suggestion
== Configure the <repository> Section
```

2024-07-10 17:59 UTC, Cristian-Venticinque reviewed
Please address comments.

2024-07-10 18:25 UTC, Cristian-Venticinque commented on kafka/4.8/modules/ROOT/pages/kafka-connector-configure-confluent-example.adoc
> +== Configure the Confluent Schema Registry in the Kakfa Connector connection
```suggestion
== Configure the Confluent Schema Registry in the Kakfa Connector Connection
```

2024-07-10 18:25 UTC, Cristian-Venticinque approved these changes, later dismissed

2024-07-10 18:26 UTC, Cristian-Venticinque approved these changes, later dismissed

2024-07-10 18:37 UTC, Cristian-Venticinque approved these changes

2024-07-10 18:39 UTC, acurci-at-mulesoft approved these changes

2024-07-10 19:32 UTC, merged