W 17322762 mac einstein ai connector vh
mulesoft/docs-connectors pull request #2753
Opened 2024-12-05 00:50 UTC by valkyrie69

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2024-12-23 18:56 UTC, rstastny9 requested changes
@valkyrie69 just did a first pass at a few of the pages but it appears you haven't updated all the various sections for Agentforce (formerly Einstein). Can you let me know when these docs are ready to go (outside of the new Agent operations)?

2024-12-23 18:56 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +Anypoint Connector for Agentforce (Agentforce Connector) provides connectivity to the https://help.salesforce.com/s/articleView?id=sf.generative_ai_trust_layer.htm&type=5[Salesforce Einstein Trust La
This definition will need to be expanded as the connector will not only allow for Anypoint developers to integrate their applications with LLMs via the Einstein Trust Layer (original Einstein AI Connector functionality) but also invoke agents running in Salesforce.

2024-12-23 18:56 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +* Build AI Agents in a no-code environment
Shouldn't this be low-code not no-code?

2024-12-23 18:56 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +== Common Use Cases for the Connector
@valkyrie69 I know this is how this section was organized previously but I'm wondering if we should consider alternatives...especially knowing that we'll be adding support for new operations

2024-12-23 18:56 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-config-acb.adoc
> +. Select the `ms-aichain:config` snippet:
This should be updated from the aichain snippet to Agentforce

2024-12-23 18:56 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-studio.adoc
> +:exchange-search-name: mulesoft ai chain
This reference needs updating as well

2024-12-23 18:56 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-studio.adoc
> +. In *Mule Palette*, click *(X) Search in Exchange*.
Note: This experience will change once the Agentforce Connector is bundled with ACB

2024-12-23 18:56 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-studio.adoc
> +. On the properties screen for the operation, click the Add (*+*) icon  to access the global element configuration fields.
This configuration steps are still yet to be updated right? These appear to be c&ped from the original Mule AI Chain connector

2025-02-07 17:40 UTC, valkyrie69 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-config-acb.adoc
> +== Configure the Trigger For the Flow
```suggestion
== Configure the Trigger For the Flows
```

2025-02-11 19:41 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +Anypoint Connector for Agentforce (Agentforce Connector) provides connectivity to the AI agents running in Salesforce’s Agentforce platform.
Anypoint Connector for Agentforce (Agentforce Connector) provides MuleSoft developers with the ability to seamlessly integrate with AI agents running in Salesforce’s Agentforce platform.

2025-02-11 20:00 UTC, rstastny9 submitted a review, later dismissed
Let's start there with the changes, let me know if you have any questions/concerns with any of the provided feedback!

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +* Surface a prompt from an external application to an agent running in Salesforce
Maybe we combine bullet 3 and 4 to read "Extend the power of Agentforce by surfacing prompts from external applications to AI agents running in Salesforce"

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +Anypoint Connector for Agentforce (Agentforce Connector) provides connectivity to the AI agents running in Salesforce’s Agentforce platform.
Anypoint Connector for Agentforce (Agentforce Connector) provides MuleSoft developers with the ability to seamlessly integrate with AI agents running in Salesforce’s Agentforce platform.

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +For information about compatibility and fixed issues, see the Agentforce Connector release notes.
Will "Agentforce Connector release notes" be a link?

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +Increase human agents' productivity by having AI agents to complete time consuming tasks such as reviewing case history, analyzing reported issues and looking up other related information.
Update to "Increase human agents' productivity by having AI agents complete time consuming tasks such as reviewing case history, analyzing reported issues and looking up other related information." 

All I removed was the word "to" before "complete time"

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +== Next Step
I'm assuming you'll be updating the "Next Step" and "See Also" sections to include valid links @valkyrie69?

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/configuring-agent-operations.adoc
> +The *Start agent conversation* operation opens the connection between the app and the agent.
The *Start agent conversation* operation establishes the connection between the app and the agent. This is the first step to enable an external application to interact with the AI agent. 

Lmk what you think of this revision @valkyrie69

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/configuring-agent-operations.adoc
> +Select the agent to invoke. The lists shows only agents that are currently active in the org.
Select the agent to invoke. The lists shows only agents that are currently active in the org (the connector filters out any agents that are not in "active" state).

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/configuring-agent-operations.adoc
> +The *Continue agent conversation* operation sends information to the agent, which maintains context within a conversation so it can follow the flow of the conversation and respond relevantly to subse
The *Continue agent conversation* operation allows for the surfacing of the message from the MuleSoft application to the agent. The agent will maintain the context of the conversation and will provide a relevant response/actions per the user's input.

Maybe something like this?

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-studio.adoc
> +:exchange-search-name: mulesoft ai chain
@valkyrie69 we need to update this to remove mention of MuleSoft AI Chain

2025-02-11 20:00 UTC, rstastny9 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-reference.adoc
> +[[Config_OauthClientCredentials]]
@valkyrie69 how did you create this section? Is this from a legacy connector or did you update it for the specifics of the Agentforce Connector?

2025-02-11 22:23 UTC, valkyrie69 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-studio.adoc
> +. In *Mule Palette*, click *(X) Search in Exchange*.
Yep. We'll need to update in March.

2025-02-11 22:25 UTC, valkyrie69 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-studio.adoc
> +. On the properties screen for the operation, click the Add (*+*) icon  to access the global element configuration fields.
These steps are always the same across connectors.

2025-02-11 22:28 UTC, valkyrie69 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +For information about compatibility and fixed issues, see the Agentforce Connector release notes.
No. Just because the RNs link is already on the page in the box on the right. We decided not to use links here because it's already linked.

2025-02-11 22:29 UTC, valkyrie69 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +== Next Step
The links are valid. Links don't work in PRs.

2025-02-11 22:30 UTC, valkyrie69 commented on agentforce/1.0/modules/ROOT/pages/configuring-agent-operations.adoc
> +The *Start agent conversation* operation opens the connection between the app and the agent.
I think it's fabulous!

2025-02-11 22:33 UTC, valkyrie69 commented on agentforce/1.0/modules/ROOT/pages/configuring-agent-operations.adoc
> +The *Continue agent conversation* operation sends information to the agent, which maintains context within a conversation so it can follow the flow of the conversation and respond relevantly to subse
I kept the gist and made minor tweaks to match our style guidelines.

2025-02-11 22:33 UTC, valkyrie69 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-reference.adoc
> +[[Config_OauthClientCredentials]]
This is the same as all connector references--it is generated. I don't create it.

2025-02-12 00:54 UTC, valkyrie69 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +Anypoint Connector for Agentforce (Agentforce Connector) provides connectivity to the https://help.salesforce.com/s/articleView?id=sf.generative_ai_trust_layer.htm&type=5[Salesforce Einstein Trust La
We'll update in the future.

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +Agentforce Connector offers a group of capabilities that simplifies agent integration in MuleSoft applications.
```suggestion
Agentforce Connector offers a group of capabilities that simplify agent integration in MuleSoft applications.
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +* Build AI Agents in a low-code environment.
```suggestion
* Build AI agents in a low-code environment.
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +* Have the credentials to connect with your Salesforce org
```suggestion
* Credentials to connect with your Salesforce org
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/index.adoc
> +Increase human agents' productivity by having AI agents complete time consuming tasks such as reviewing case history, analyzing reported issues and looking up other related information.
```suggestion
Increase human agents' productivity by having AI agents complete time-consuming tasks such as reviewing case history, analyzing reported issues, and looking up other related information.
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-studio.adoc
> +. In *Add Dependencies to Project*, type `mulesoft agentforce` in the search field.
```suggestion
. In *Add Dependencies to Project*, type `agentforce` in the search field.
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-studio.adoc
> +You can configure one of these sources to use with MuleSoft Chain AI Connector:
```suggestion
You can configure one of these sources to use with Agentforce Connector:
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/configuring-agent-operations.adoc
> +Select the agent to invoke. The lists shows only agents that are currently active in the org. The connector filters out any agents that aren't in the `active` state.
```suggestion
Select the agent to invoke. The list shows only agents that are currently active in the org. The connector filters out any agents that aren't in the `active` state.
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-xml-maven.adoc
> +. In Exchange, search for `muleSoft agentforce`.
```suggestion
. In Exchange, search for `agentforce`.
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-xml-maven.adoc
> +* xref:agentforce-additional-config.adoc[Agentforce Connector - Additional Configuration]
```suggestion
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-reference.adoc
> +| Token Url a| String |  The service provider's token endpoint URL |  https://{salesforceorg}/services/oauth2/token |
```suggestion
| Token Url a| String |  The service provider's token endpoint URL. |  `\https://{salesforceorg}/services/oauth2/token` | 
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-reference.adoc
> +[%header%autowidth.spread]
replace all [%header%autowidth.spread] with [%header,cols="20s,25a,30a,15a,10a"]

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-reference.adoc
> +| Error Mappings a| Array of <<ErrorMapping>> |  Set of error mappings |  |
```suggestion
| Error Mappings a| Array of <<ErrorMapping>> |  Set of error mappings. |  | 
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-reference.adoc
> +| Output Mime Type a| String |  The mime type of the payload that this operation outputs. |  |
```suggestion
| Output Mime Type a| String |  MIME type of the payload that this operation outputs. |  | 
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-reference.adoc
> +| Initial Buffer Size a| Number | Initial amount of memory to allocate to the data stream. If the streamed data exceeds this value, the buffer expands by *Buffer Size Increment*, with an upper limit
```suggestion
| Initial Buffer Size a| Number | Initial amount of memory to allocate to the data stream. If the streamed data exceeds this value, the buffer expands by *Buffer Size Increment*, with an upper limit of *Max Buffer Size*. |  | 
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-reference.adoc
> +** GB | Unit for the *Initial Buffer Size*, *Buffer Size Increment*, and *Buffer Unit* fields. |  |
```suggestion
** GB | Unit for the *Initial Buffer Size*, *Buffer Size Increment*, and *Max Buffer Size* fields. |  | 
```

2025-02-12 23:39 UTC, sathya0 commented on agentforce/1.0/modules/ROOT/pages/agentforce-connector-reference.adoc
> +* xref:einstein-ai-connector-reference.adoc[Agentforce Connector Reference]
```suggestion
```

2025-02-13 00:24 UTC, sathya0 approved these changes, later dismissed

2025-02-20 16:41 UTC, dmerlob approved these changes

2025-02-20 16:43 UTC, merged