Docs 5031 Web Service Consumer Reference 1.5
mulesoft/docs-connectors pull request #348
Opened 2019-09-06 14:44 UTC by valkyrie69

2019-09-06 16:19 UTC, Bardammu commented on modules/ROOT/pages/web-service/web-service-consumer-configure.adoc
> +The Web Service Consumer Connector has a single configuration. The most important configuration parameters are the the WSDL Location (`wsdlLocation`), the Service (`service`), and the Port (`port`).
Remove one `the`

2019-09-06 16:34 UTC, Bardammu requested changes
There is just a typo

2019-09-10 00:57 UTC, Bardammu approved these changes
LGTM

2019-09-10 13:25 UTC, kevintroller approved these changes
LGTM

2019-09-10 14:38 UTC, merged