update metadata for connectors
mulesoft/docs-connectors pull request #658
Opened 2020-02-22 00:28 UTC by mojavelinux

- add missing exchange URLs
- add missing release notes xrefs
- add or fix support levels
- fix inconsistent titles
- fix inconsistent descriptions

2020-02-22 00:30 UTC, mojavelinux commented
These changes provide the necessary information for the migration script to accurately migrate the connectors to the new structure. cc: @sleslie23

2020-02-25 17:31 UTC, valkyrie69 requested changes

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/aggregator/aggregators-module.adoc
> +The Aggregators Module contains different types of aggregators capable of storing values and releasing them all together based on the configuration specified. An aggregator is a component used to col
```suggestion
Aggregators Module contains different types of aggregators capable of storing values and releasing them all together based on the configuration specified. An aggregator is a component used to collect those values until a condition is met, then execute a processor’s chain with the list of aggregated elements as the payload.
```

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/amazon/amazon-s3-connector-reference.adoc
> +Exchange: https://anypoint.mulesoft.com/exchange/com.mulesoft.connectors/mule-amazon-s3-connector[Amazon S3 connector in Anypoint Exchange]
Exchange link was intentionally removed. We don't want it at the top of the page.

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/anypoint-mq/3.x/anypoint-mq-connector.adoc
> +Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/anypoint-mq-connector/[Anypoint MQ Connector 3.x — Mule 4]
Should be in See Also not the top of the page

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/anypoint-mq/3.x/anypoint-mq-connector.adoc
> +Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/anypoint-mq-connector/[Anypoint MQ Connector 3.x — Mule 4]
Should be in See Also not the top of the page

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/as2/as2-connector-reference.adoc
> +Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-as2-connector/[AS2 Connector]
Move to See Also

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/as2/as2-connectorMule4.adoc
> +Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-as2-connector/[AS2 Connector]
Move to See Also

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/compression/compression-module.adoc
> +The Compression Module supports and provides access to the most-used
No "the" on any of the connectors. It is Compression Module

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/edifact/edifact-edi-connector.adoc
> +Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-edifact-extension/[EDIFACT EDI Connector]
All of these Exchange links are being moved to the See Also section at the bottom of the page. They were intentionally removed from the top of the file.

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/nav.adoc
> +* xref:oauth/oauth-documentation.adoc[OAuth Module]
Both of these should have "Reference" in the title. They are references.

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/aggregator/aggregators-module.adoc
> +The Aggregators Module contains different types of aggregators capable of storing values and releasing them all together based on the configuration specified. An aggregator is a component used to col
Aggregators Module. No "The"

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/pages/amazon/amazon-s3-connector-reference.adoc
> +Exchange: https://anypoint.mulesoft.com/exchange/com.mulesoft.connectors/mule-amazon-s3-connector[Amazon S3 connector in Anypoint Exchange]
Exchange link should be in See Also

2020-02-25 17:31 UTC, valkyrie69 commented on modules/ROOT/nav.adoc
> +* xref:oauth/oauth2-provider-documentation-reference.adoc[OAuth2 Provider Module]
"Reference" should be in. These are references docs.

2020-02-27 03:16 UTC, mojavelinux commented
@valkyrie69 I believe I have made all the changes you requested. The update also fixes numerous broken xrefs and image refs, which were validated by the migration script. If you need me to make any other changes, don't hesitate to request them.

2020-02-28 23:23 UTC, valkyrie69 approved these changes

2020-03-04 21:42 UTC, merged