Added a better description to Web Service Endpoint URL field to fix a bug
mulesoft/docs-connectors pull request #675
Opened 2020-03-05 15:13 UTC by dhirsch1

I also did the following:

- Removed and renamed the duplicate headings for  Operations and Sources.

- Removed the duplicate listing of standard (non-RESTlet-specific) operations and sources and used links instead.

2020-03-05 16:44 UTC, agustinmiura requested changes
The links for the menus that link to the operations aren't working . Could you please fix that ?

2020-03-05 18:22 UTC, agustinmiura approved these changes

2020-03-06 14:09 UTC, kevintroller commented on modules/ROOT/pages/netsuite/netsuite-reference.adoc
> +| Host a| String |  The hostname of the HTTP proxy, for example localhost This field also requires the port to be set. |  |
for example localhost This field > for example localhost**.** This field
Missing (.dot)

2020-03-06 14:21 UTC, kevintroller approved these changes

2020-03-06 20:09 UTC, merged