MULE-18105:Sockets Connector User Guide Needs Connection Information.
mulesoft/docs-connectors pull request #702
Opened 2020-04-06 16:19 UTC by emariotti3

2020-04-07 17:21 UTC, marianogonzalez requested changes

2020-04-07 17:21 UTC, marianogonzalez commented on modules/ROOT/pages/sockets/sockets-connector-examples.adoc
> +		<set-payload value="#[output application/json --- 'name': payload[0].FIRST_NAME as String ++ ' ' ++ payload[0].LAST_NAME as String]" doc:name="Set Payload" />
delete this. Perform this transformation in the `<sockets:content>` tag below

2020-04-07 17:21 UTC, marianogonzalez commented on modules/ROOT/pages/sockets/sockets-connector-examples.adoc
> +		<set-payload value="#[output application/json --- 'name': payload[0].FIRST_NAME as String ++ ' ' ++ payload[0].LAST_NAME as String]" doc:name="Set Payload"  />
use `<ee:transform>` instead

2020-04-07 17:21 UTC, marianogonzalez commented on modules/ROOT/pages/sockets/sockets-connector-examples.adoc
> +		  <file:content><![CDATA[#[payload]
redundant

2020-04-07 17:21 UTC, marianogonzalez commented on modules/ROOT/pages/sockets/sockets-connector-examples.adoc
> +		<file:write path="musicians.txt" config-ref="File_Config" mode="CREATE_NEW">
you're wrting a json with `txt` extension. People will get confused by this

2020-04-07 19:57 UTC, marianogonzalez approved these changes

2020-04-17 20:30 UTC, kevintroller approved these changes
Approved, updated wording - styling.

2020-04-17 20:30 UTC, merged