added supported JCO library version
mulesoft/docs-connectors pull request #764
Opened 2020-05-19 13:56 UTC by Santaionut

2020-05-19 18:16 UTC, valkyrie69 approved these changes

2020-05-20 04:52 UTC, sorinmare commented on modules/ROOT/pages/sap/sap-connector-studio.adoc
> +SAP Connector supports only version 3.0.x SAP libraries.
SAP Connector - Mule 4 supports only versions 3.0.x of SAP JCo libraries.

2020-05-20 04:54 UTC, sorinmare requested changes
Also, the note with the supported versions should be at the end of "Install SAP Libraries" chapter.

2020-05-20 05:12 UTC, sorinmare approved these changes

2020-05-20 08:23 UTC, FilipBogdanSV approved these changes

2020-05-20 15:17 UTC, valkyrie69 approved these changes

2020-05-20 15:18 UTC, merged