Microsoft Dynamics 364 v2.4
mulesoft/docs-connectors pull request #975
Opened 2020-08-18 14:43 UTC by dhirsch1

2020-09-09 07:59 UTC, irinel-dan requested changes

2020-09-09 07:59 UTC, irinel-dan commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +|===
>>>>>> Stashed changes - this looks like an unresolved merge conflict.

2020-09-09 07:59 UTC, irinel-dan commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-xml-maven.adoc
> +  <artifactId>mule-sap-connector</artifactId>
this should be
`<artifactId>mule-microsoft-dynamics365-connector</artifactId>`

2020-09-10 07:50 UTC, irinel-dan submitted a review, later dismissed

2020-09-10 08:20 UTC, catalinbarakat submitted a review, later dismissed

2020-09-10 16:59 UTC, valkyrie69 approved these changes, later dismissed

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-studio.adoc
> +
This is the old template. We should make a list of connectors that need to be updated to match the current template.

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-xml-maven.adoc
> +If you manually code a Mule app in XML either from the Anypoint Studio XML editor or from a text editor, you can get access to the Microsoft Dynamics 365 Connector in your app by adding reference sta
Outdated template

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Scopes a| String |  The OAuth scopes to be requested during the dance. If not provided, this value defaults to the scopes in the annotation. |  |
```suggestion
| Scopes a| String |  The OAuth scopes to request during the dance. If not provided, this value defaults to the scopes in the annotation. |  |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Resource Owner Id a| String |  The ID each component should use if it doesn't have another reference. |  |
What is "it"? 

The ID each component should use if the component doesn't have a reference to a resource owner ID? 

I'm not sure.

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Before a| String |  The name of a flow to execute right before starting the OAuth dance. |  |
```suggestion
| Before a| String |  The name of a flow to execute immediately before starting the OAuth dance. |  |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| After a| String |  The name of a flow to execute right after an accessToken is received. |  |
```suggestion
| After a| String |  The name of a flow to execute immediately after an accessToken is received. |  |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Username a| String |  Username used to authenticate against the proxy. If this property is not set then no authentication is going to use against the proxy, otherwise this value must be specified.
```suggestion
| Username a| String |  Username used to authenticate against the proxy. If this property is not set, then no authentication is used against the proxy.  |  |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Use Single Transaction a| Boolean |  Use a single transaction for deletion. If the deletion fails, the transaction is rolled-back. |  true |
```suggestion
| Use Single Transaction a| Boolean |  Use a single transaction for deletion. If the deletion fails, the transaction is rolled back. |  true |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Datasense Query a| String |  The DSQL query that is going to use for retrieve. The query will be transformed in a retrieve URL internally. |  | x
```suggestion
| Datasense Query a| String |  The DSQL query to use to retrieve. The query is transformed in a retrieve URL internally. |  | x
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Use Single Transaction a| Boolean |  Use a single transaction for update. If the update fails, the transaction is rolled-back. |  false |
```suggestion
| Use Single Transaction a| Boolean |  Use a single transaction for an update. If the update fails, the transaction is rolled back. |  false |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Primary Node Only a| Boolean |  Whether this source should be executed on the primary node only when running in a cluster. |  |
```suggestion
| Primary Node Only a| Boolean |  Whether to execute this source on only the primary node when running in a cluster. |  |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Primary Node Only a| Boolean |  Whether this source should only be executed on the primary node when running in a cluster. |  |
```suggestion
| Primary Node Only a| Boolean |  Whether to execute this source on only the primary node when running in a cluster. |  |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Message Digest Algorithm a| String | The secure hashing algorithm to use. If not set, the default is `SHA-256`. |  |
```suggestion
| Message Digest Algorithm a| String | The secure hashing algorithm to use.  | `SHA-256` |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Initial Buffer Size a| Number | The number of instances to keep in memory to consume the stream and provide random access to it. If the stream contains more data than can fit into this buffer, then
```suggestion
| Initial Buffer Size a| Number | The number of instances to keep in memory to consume the stream and provide random access to it. If the stream contains more data than can fit into this buffer, then it expands according to the bufferSizeIncrement attribute, with an upper limit of Max In Memory Size. Default value is 100 instances. | 100  |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Buffer Size Increment a| Number | By how much the buffer size by expands if it exceeds its initial size. Setting a value of zero or lower means that the buffer should not expand, meaning that a STR
```suggestion
| Buffer Size Increment a| Number | Specifies how much the buffer size expands if it exceeds its initial specified size. Setting a value of zero or lower means that the buffer should not expand, and that a STREAM_MAXIMUM_SIZE_EXCEEDED error is raised when the buffer gets full. Default value is 100 instances. |100  |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Max Buffer Size a| Number | The maximum amount of memory to use. If more memory is used, a STREAM_MAXIMUM_SIZE_EXCEEDED error is raised. A value lower or equal to zero means no limit. |  |
```suggestion
| Max Buffer Size a| Number | The maximum amount of memory to use. If more memory is used, a STREAM_MAXIMUM_SIZE_EXCEEDED error is raised. A value of zero or lower means no limit. |  |
```

2020-09-10 16:59 UTC, valkyrie69 commented on microsoft-dynamics-365/2.4/modules/ROOT/pages/microsoft-dynamics-365-connector-reference.adoc
> +| Max In Memory Size a| Number | The maximum amount of instances that are kept in memory. If more instances are required, then the connector starts to buffer the content on disk. |  |
```suggestion
| Max In Memory Size a| Number | The maximum number of instances that are kept in memory. If more instances are required, then the connector starts to buffer the contents onto disk. |  |
```

2020-09-10 17:43 UTC, valkyrie69 approved these changes

2020-09-10 17:46 UTC, merged